### ISSUE TITLE
关于 直播间M3U文件生成器无法添加个别主播的问题

### ISSUE THREAD

**Issue by MEMEDADADA** [YanG-1989/m3u#100]
刚才试了下 直播间M3U文件生成器，无法添加与辉同行直播间。怀疑是不是如果抖音号是数字的话，就无法生成？如果抖音号是字母，就可以添加？谁知道怎么解决吗？

**Comment by YanG-1989** [comment]
> 刚才试了下 直播间M3U文件生成器，无法添加与辉同行直播间。怀疑是不是如果抖音号是数字的话，就无法生成？如果抖音号是字母，就可以添加？谁知道怎么解决吗？

这个直播间不是早就有了吗？

**Comment by YanG-1989** [comment]
重复的id是不能添加的..

**Comment by MEMEDADADA** [comment]
不明白哪里重复了？该怎么解决？

大葱 ***@***.***> 于2024年8月22日周四 14:49写道：

**Comment by YanG-1989** [comment]
> 不明白哪里重复了？该怎么解决？
> 
> 
说明你要加的主播已经在订阅里面了，昨天优化了在线主播的脚本..现在应该能正常显示在线了。
