### ISSUE TITLE
江苏电信，IPV6只能播放CCTV的资源，其他频道几乎都没有速度，一直转圈，或者非常卡

### ISSUE THREAD

**Issue by Walking87** [YanG-1989/m3u#102]
求助大佬，一直用您分享的源，但是最近，江苏电信，IPV6只能播放CCTV的资源，其他频道几乎都没有速度，一直转圈，或者非常卡

**Comment by Walking87** [comment]
感谢大佬的回复。硬件上的原因那也没办法了。时好时坏，估计跟我们地方上的电信有关，奥运期间白天正常，晚上ppt

**Comment by YanG-1989** [comment]
几个月就开始了..联通比电信早一点开始。
每个地区的情况不一样。
目前高峰期，对非移动运营商都进行了限速。
但是可以通过dns劫持方式达到正常。
方法在 pixman.io 里面你自己有兴趣的话去看看。
