### ISSUE TITLE
sports

### ISSUE THREAD

**Issue by 17731219951** [YanG-1989/m3u#104]
那些英文的体育台还会有么

**Comment by YanG-1989** [comment]
> 那些英文的体育台还会有么
> 
看大佬维不维护了！
有的话，我会加到主页里面去...

**Comment by 17731219951** [comment]
好的，谢谢你，订阅的电视台有的能看有的地址不一致，是什么情况
---- Replied Message ----
***@***.***>Date08/31/2024 19:21 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [YanG-1989/m3u] sports (Issue #104)
那些英文的体育台还会有么
看大佬维不维护了！
有的话，我会加到主页里面去...

**Comment by YanG-1989** [comment]
自己看其他帖子，已经有说明啦！
