### ISSUE TITLE
体育订阅需要名字验证

### ISSUE THREAD

**Issue by tjchocolate** [YanG-1989/m3u#109]

**Comment by YanG-1989** [comment]
你都在GitHub留言了..
还不知道名字吗？

**Comment by tjchocolate** [comment]
我写的大葱、不对、哈哈是哪个
对了、还有个问题、手机移动网络、订阅后看不了呢？都是超时

**Comment by tjchocolate** [comment]
名字填对了、谢谢
移动网络咋订阅后看不了呢

**Comment by YanG-1989** [comment]
> 名字填对了、谢谢
> 移动网络咋订阅后看不了呢

你说咪咕移动吧？ 需要移动运营商

**Comment by tjchocolate** [comment]
您好：订阅之后不用家里的网路、用手机中国移动的移动网络、显示超时呢、是哪里设定不对吗？


在 2024年9月11日，10:42，大葱 ***@***.***> 写道：

﻿

名字填对了、谢谢
移动网络咋订阅后看不了呢

你说咪咕移动吧？ 需要移动运营商

**Comment by tjchocolate** [comment]
您好：移动网络能看了、感谢
           是换别的地方的Wi-Fi就看不了了吗？
发自我的 iPhone

在 2024年9月11日，10:42，大葱 ***@***.***> 写道：

﻿

名字填对了、谢谢
移动网络咋订阅后看不了呢

你说咪咕移动吧？ 需要移动运营商
