### ISSUE TITLE
大佬如果有空的话，希望能加几个主播，非常感谢！

### ISSUE THREAD

**Issue by JeansTulovski** [YanG-1989/m3u#11]
ya 赤小兔 303517
yu 驴哥LvGe 5110403
yu 一本稻 300358

**Comment by YanG-1989** [comment]
> ya 赤小兔 303517
> 
> yu 驴哥LvGe 5110403
> 
> yu 一本稻 300358

搞定了...其实你自己弄集合也行！
我在考虑要不要把yu和ya集合在一起
