### ISSUE TITLE
现在的凤凰卫视资讯所有地址都无法观看，请回复~！~~~

### ISSUE THREAD

**Issue by sy007007** [YanG-1989/m3u#110]
现在的所有地址都无法观看，请回复~！~~~

我只看凤凰卫视资讯台，请更新凤凰卫视资讯地址~~~

**Comment by YanG-1989** [comment]
> 现在的所有地址都无法观看，请回复~！~~~
> 
> 
> 
> 我只看凤凰卫视资讯台，请更新凤凰卫视资讯地址~~~

凤凰正常啊..但是只有720p

**Comment by YanG-1989** [comment]
就是港澳 分组里面的...正常

**Comment by YanG-1989** [comment]
> https://tv.iill.top/phenix/fhzx
> 
> 
> 
> https://tv.iill.top/MyTV/PIN
> 
> 
> 
> https://tv.iill.top/MyTV/PIN
> 
> 
> 
> 以上三个链接用代理也打不开~~~
> 
> 
> 
> 

你都不看订阅分组和频道名称的上面的字？
还有自己去看下..更新公告

**Comment by sy007007** [comment]
看过啦，还是打不开啊，能不能把链接发给我

**Comment by YanG-1989** [comment]
> 看过啦，还是打不开啊，能不能把链接发给我 

一个限制ua，一个需要mpd

你看过啥？看懂了吗？
链接你自己不是发了吗？

**Comment by sy007007** [comment]
请问一个限制ua，一个需要mpd是什么意思，没看懂，知识太少，抱歉抱歉~~~

**Comment by YanG-1989** [comment]
> 请问一个限制ua，一个需要mpd是什么意思，没看懂，知识太少，抱歉抱歉~~~

播放器需要支持mpd
限制ua是这个链接限制了 播放器比如 okhttp
