### ISSUE TITLE
国足直播源有吗

### ISSUE THREAD

**Issue by xp-git** [YanG-1989/m3u#111]

**Comment by zubair1511983** [comment]
yanG how to watch on Samsung smart TV using this link https://tv.iill.top/m3u/Gather

**Comment by zijilinla** [comment]
有看国足的不？

**Comment by YanG-1989** [comment]
> yanG how to watch on Samsung smart TV using this link https://tv.iill.top/m3u/Gather

支持m3u的播放器就行了...
我里面境外的源基本上没有..

**Comment by YanG-1989** [comment]
国足的到点了估计会有分享的...不用来我这里问
