### ISSUE TITLE
Live直播平台无法播放

### ISSUE THREAD

**Issue by Jezzywest** [YanG-1989/m3u#112]
一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！

**Comment by YanG-1989** [comment]
> 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！

没有吧...我看都正常
是不是我的域名在你那边墙了

**Comment by Jezzywest** [comment]
> > 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！
> 
> 没有吧...我看都正常 是不是我的域名在你那边墙了

啊，我也没有找到原因不是很懂，但是只有live的这个看不了，其他gather什么的都正常没问题。可以指导一下怎么检查嘛，万分感谢！（真的很好用）

**Comment by YanG-1989** [comment]
> > > 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！
> 
> > 
> 
> > 没有吧...我看都正常 是不是我的域名在你那边墙了
> 
> 
> 
> 啊，我也没有找到原因不是很懂，但是只有live的这个看不了，其他gather什么的都正常没问题。可以指导一下怎么检查嘛，万分感谢！（真的很好用）

现在还是看不了吗？
你直接把live.iill.top 打得开吗

**Comment by Jezzywest** [comment]
> > > > 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！
> > 
> > 
> > > 
> > 
> > 
> > > 没有吧...我看都正常 是不是我的域名在你那边墙了
> > 
> > 
> > 啊，我也没有找到原因不是很懂，但是只有live的这个看不了，其他gather什么的都正常没问题。可以指导一下怎么检查嘛，万分感谢！（真的很好用）
> 
> 现在还是看不了吗？ 你直接把live.iill.top 打得开吗

对，还是看不了，这个网址上的了，刚刚tivimate上面点更新显示格式错误无法更新，重新添加也添加不了了。

**Comment by Jezzywest** [comment]
> > > > > 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 没有吧...我看都正常 是不是我的域名在你那边墙了
> > > 
> > > 
> > > 啊，我也没有找到原因不是很懂，但是只有live的这个看不了，其他gather什么的都正常没问题。可以指导一下怎么检查嘛，万分感谢！（真的很好用）
> > 
> > 
> > 现在还是看不了吗？ 你直接把live.iill.top 打得开吗
> 
> 对，还是看不了，这个网址上的了，刚刚tivimate上面点更新显示格式错误无法更新，重新添加也添加不了了。

哥！我找到问题了，是我华硕路由上的ss模式有问题，我换了模式或者全局就可以看了，应该是之前被拦截了。

**Comment by YanG-1989** [comment]
> > > > > > 一直都在使用，挺好用的，前两天突然全部看不了了，也没有显示格式错误，就是一直在转圈，更新和重新添加都不行。尝试其他端也是同样的问题，求大佬解答～感谢！
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > 没有吧...我看都正常 是不是我的域名在你那边墙了
> 
> > > > 
> 
> > > > 
> 
> > > > 啊，我也没有找到原因不是很懂，但是只有live的这个看不了，其他gather什么的都正常没问题。可以指导一下怎么检查嘛，万分感谢！（真的很好用）
> 
> > > 
> 
> > > 
> 
> > > 现在还是看不了吗？ 你直接把live.iill.top 打得开吗
> 
> > 
> 
> > 对，还是看不了，这个网址上的了，刚刚tivimate上面点更新显示格式错误无法更新，重新添加也添加不了了。
> 
> 
> 
> 哥！我找到问题了，是我华硕路由上的ss模式有问题，我换了模式或者全局就可以看了，应该是之前被拦截了。

好的..那就没问题了..囧
