### ISSUE TITLE
限制IPV6中的内容是不能观看的吗

### ISSUE THREAD

**Issue by FernandoGEE** [YanG-1989/m3u#114]
大佬，限制IPV6中的内容是不能观看的吗
![IMG_0139](https://github.com/user-attachments/assets/24bc2ec1-9115-4249-8056-8be9d130cc73)

**Comment by YanG-1989** [comment]
> 大佬，限制IPV6中的内容是不能观看的吗
> 
> ![IMG_0139](https://github.com/user-attachments/assets/24bc2ec1-9115-4249-8056-8be9d130cc73)
> 
> 

目前好像只能移动网络才可以观看...
其他运营商给限制了😮‍💨

**Comment by FernandoGEE** [comment]
谢啦
