### ISSUE TITLE
突然连接不上了，人在海外

### ISSUE THREAD

**Issue by JoeyChen027** [YanG-1989/m3u#115]
之前您的源一直用的很稳定，但是几天前突然连不上了，一直到现在，人在国外，是被墙了嘛？

**Comment by YanG-1989** [comment]
> 之前您的源一直用的很稳定，但是几天前突然连不上了，一直到现在，人在国外，是被墙了嘛？

在国外不会吧？ 网站能打开吗？

**Comment by YanG-1989** [comment]
你不会一直刷新订阅，给拉黑名单了吧😏

**Comment by JoeyChen027** [comment]
我没用过那个订阅网站，我是直接找m3u raw的url，也就是https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u，把这个贴我电视上播放器的playlist里的。

**Comment by YanG-1989** [comment]
> 我没用过那个订阅网站，我是直接找m3u raw的url，也就是https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u，把这个贴我电视上播放器的playlist里的。

https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u

你raw错了吧...

**Comment by JoeyChen027** [comment]
我是这方面的小白，我就是网上看到的方法，自己捣鼓着试试，所以请问你觉得应该是哪个url呢？我电视上的app叫Bob player，只能是在playlist里添加自己找的源的url，还请大神指点，我家小朋友现在都没法看电视了。。。谢谢

**Comment by YanG-1989** [comment]
> 我是这方面的小白，我就是网上看到的方法，自己捣鼓着试试，所以请问你觉得应该是哪个url呢？我电视上的app叫Bob player，只能是在playlist里添加自己找的源的url，还请大神指点，我家小朋友现在都没法看电视了。。。谢谢

国外不好看国内源吧..GitHub上面找找吧，BOb palyer 我也没用过.
一般人家都有订阅地址  放进去就行了

**Comment by jinhao81** [comment]
我也想请问一下，ott和影视tv里面突然都解析不出来频道了，都没改过配置，也挂上了梯子，全部显示错误，而在电脑端potplayer里面却能正常播放。

https://github.com/user-attachments/assets/9e3dd9af-407d-47ee-98ea-6718a7381921

**Comment by YanG-1989** [comment]
> 我也想请问一下，ott和影视tv里面突然都解析不出来频道了，都没改过配置，也挂上了梯子，全部显示错误，而在电脑端potplayer里面却能正常播放。
> 
> 
> 
> https://github.com/user-attachments/assets/9e3dd9af-407d-47ee-98ea-6718a7381921
> 
> 
> 
> 

不清楚..我试过影视正常.
你影视正常吗？ott本来就需要设置
