### ISSUE TITLE
tivimate发生错误

### ISSUE THREAD

**Issue by BiancaFang** [YanG-1989/m3u#117]
今天在tivimate5.1.0上打开任一频道一直在重试，显示：Unrecognized Input Format Exception.

**Comment by BiancaFang** [comment]
好像只是体育列表出现这种情况

**Comment by YanG-1989** [comment]
> 好像只是体育列表出现这种情况

sport这个订阅是吧..经常坏的习惯了就好

**Comment by BiancaFang** [comment]
现在又好了，可能是之前源挂了
