### ISSUE TITLE
原本能看的sub直接显示the end..

### ISSUE THREAD

**Issue by stevenchansn** [YanG-1989/m3u#118]
如题，是因为这个sub停止维护了么….

**Comment by YanG-1989** [comment]
> 如题，是因为这个sub停止维护了么….
> 
> 

你说体育订阅吧..
这个经常坏的...
大佬什么时候维护好..什么时候才能看

**Comment by stevenchansn** [comment]
> > 如题，是因为这个sub停止维护了么….
> 
> 你说体育订阅吧.. 这个经常坏的... 大佬什么时候维护好..什么时候才能看

mmmmmmm 好的吧🥲
