### ISSUE TITLE
大佬能不能加一个md少年阿宾

### ISSUE THREAD

**Issue by dissaplay** [YanG-1989/m3u#12]
能不能加一个md少年啊宾的m3u8 呀，谢谢大佬

**Comment by YanG-1989** [comment]
> 能不能加一个md少年啊宾的m3u8 呀，谢谢大佬

都不知道是啥？主播？

**Comment by GD2021** [comment]
他的意思是麻豆传媒的大型连续剧<少年阿宾>

**Comment by YanG-1989** [comment]
> 他的意思是麻豆传媒的大型连续剧<少年阿宾>

原来如此，我去安排安排

**Comment by dissaplay** [comment]
谢谢大佬，研发出来了吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月23日(星期四) 晚上7:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YanG-1989/m3u] 大佬能不能加一个md少年阿宾 (Issue #12)





  
能不能加一个md少年啊宾的m3u8 呀，谢谢大佬
  
只发现1-8章，缺了第4。有空帮你加到其他分组里面。
 
&mdash;

**Comment by dissaplay** [comment]
大佬能不能再搞个韩国的3j 片的合集，嘻嘻嘻







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanG-1989/m3u"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上6:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YanG-1989/m3u] 大佬能不能加一个md少年阿宾 (Issue #12)





 
你自己更新下订阅不就看到了？
