### ISSUE TITLE
网站

### ISSUE THREAD

**Issue by yuki925** [YanG-1989/m3u#120]
有两次历史记录 二次上传依旧是等待系统更新 请问是我网络不好还是手机情况呢

**Comment by YanG-1989** [comment]
> 有两次历史记录 二次上传依旧是等待系统更新 请问是我网络不好还是手机情况呢

一般添加后..15分钟左右更新.
前提是他要在线..
主播叫什么？有些浏览器会拦截数据。

**Comment by yujianmantuluo** [comment]
请问大佬能搞腾讯nba的源吗

**Comment by YanG-1989** [comment]
> 请问大佬能搞腾讯nba的源吗

没会员账号，咪咕有的看就不错了

**Comment by yujianmantuluo** [comment]
有会员账号怎么弄，可以简单说下吗，具体的我可以上网搜。目前盲目搜，无从下手

**Comment by yujianmantuluo** [comment]
> > 请问大佬能搞腾讯nba的源吗
> 
> 没会员账号，咪咕有的看就不错了

有会员账号怎么弄，可以简单说下吗，具体的我可以上网搜。目前盲目搜，无从下手

**Comment by yuki925** [comment]
是谷歌会拦截吗 难怪我尝试很多次都没有成功😢

**Comment by YanG-1989** [comment]
> 是谷歌会拦截吗 难怪我尝试很多次都没有成功😢

不清楚..反正我不会拦截..

**Comment by YanG-1989** [comment]
> > > 请问大佬能搞腾讯nba的源吗
> 
> > 
> 
> > 没会员账号，咪咕有的看就不错了
> 
> 
> 
> 有会员账号怎么弄，可以简单说下吗，具体的我可以上网搜。目前盲目搜，无从下手

https://pixman.io/topics/72

大佬的项目..

**Comment by YanG-1989** [comment]
> 是谷歌会拦截吗 难怪我尝试很多次都没有成功😢

发一个你上传过的..我查下就知道了
要不你换手机试下..

**Comment by yuki925** [comment]
狼队-一笙 大哥我之前也是这样 然后你帮我搞定的 所以我也不知道问题出在哪里

**Comment by YanG-1989** [comment]
> 狼队-一笙 大哥我之前也是这样 然后你帮我搞定的 所以我也不知道问题出在哪里

换个浏览器吧..那你还不如去aptv群里找我🙄
