### ISSUE TITLE
Tvbox无法观看部分频道

### ISSUE THREAD

**Issue by Jeremy-2024** [YanG-1989/m3u#123]
![Screenshot_2024-10-11-00-38-36-58_593da977e8f67ec1ec7eb5b38a9a60ac](https://github.com/user-attachments/assets/00ba4f27-7adc-4ad7-b9d8-ad3545bd37e1)
使用tvbox时，部分频道无法播放，例如咪咕TV、台湾等，会出现「请保持订阅IP与观看IP一致」

**Comment by YanG-1989** [comment]
> ![Screenshot_2024-10-11-00-38-36-58_593da977e8f67ec1ec7eb5b38a9a60ac](https://github.com/user-attachments/assets/00ba4f27-7adc-4ad7-b9d8-ad3545bd37e1)
> 
> 使用tvbox时，部分频道无法播放，例如咪咕TV、台湾等，会出现「请保持订阅IP与观看IP一致」

去看置顶的问题综合贴
