### ISSUE TITLE
可否添加animax频道呢

### ISSUE THREAD

**Issue by dabaisha233** [YanG-1989/m3u#124]
希望添加ipv4可以收视的animax频道

**Comment by YanG-1989** [comment]
> 希望添加ipv4可以收视的animax频道

我去看看有没有资源..

**Comment by dabaisha233** [comment]
多谢 （ｖ＾＿＾）ｖ

**Comment by YanG-1989** [comment]
> > > 希望添加ipv4可以收视的animax频道
> 
> > 
> 
> > 我去看看有没有资源..
> 
> 
> 
> 多谢 (*^▽^*) 

新加坡 这个台倒闭了吧..

**Comment by dabaisha233** [comment]
我手头上是有一个播放源不过是ipv6的
http://qwe.iptviptv.site:9694/hls/903/index.m3u8

**Comment by YanG-1989** [comment]
> 我手头上是有一个播放源不过是ipv6的
> 
> http://qwe.iptviptv.site:9694/hls/903/index.m3u8

不太了解..白嫖不到我也帮不到你。
你去 http://tonkiang.us 搜索看看..
