### ISSUE TITLE
韩国电视源

### ISSUE THREAD

**Issue by Adrian1103** [YanG-1989/m3u#126]
韩国的tvn和jtbc这样的能加进来吗，能分享一下SBS，MBC的直播源抓取方法吗

**Comment by YanG-1989** [comment]
> 韩国的tvn和jtbc这样的能加进来吗，能分享一下SBS，MBC的直播源抓取方法吗

大街源..这两个我好像看到过。
tvn 没字幕的你看得懂吗 Astro里面有

**Comment by Adrian1103** [comment]
JTBC TVN综艺好看，没字幕能看懂，就是周围的人有需求，您能把他们的源加到Gather或者其他的吗

**Comment by YanG-1989** [comment]
> JTBC TVN综艺好看，没字幕能看懂，就是周围的人有需求，您能把他们的源加到Gather或者其他的吗 

Astro里面有tvn
jtbc好像没有..
你可以考虑去
https://epg.pw
http://tonkiang.us
上面两个里面找找..虽然不稳定但是能搜到

**Comment by haoyu995** [comment]
想问一下，直播源里，afreeca的频道是不再提供了么

**Comment by YanG-1989** [comment]
> 想问一下，直播源里，afreeca的频道是不再提供了么

afreeca 他家改名字了..脚本坏了。这几天抽空看看

**Comment by YanG-1989** [comment]
搞定了..结束！
