### ISSUE TITLE
咪咕ipv4突然看不了

### ISSUE THREAD

**Issue by Mkbk75** [YanG-1989/m3u#127]
刷新配置也不行 一直是超时状态 前一阵还好好的
![2A358430-B992-425D-B96E-E5172E15E038](https://github.com/user-attachments/assets/51a31cc4-2268-4290-86b5-bc18bb1ac107)

**Comment by YanG-1989** [comment]
> 刷新配置也不行 一直是超时状态 前一阵还好好的
> 
> ![2A358430-B992-425D-B96E-E5172E15E038](https://github.com/user-attachments/assets/51a31cc4-2268-4290-86b5-bc18bb1ac107)
> 
> 
晚上 我把老的加回去...
