### ISSUE TITLE
希望YanG大佬能在咪咕足球栏里加个中甲的赛程

### ISSUE THREAD

**Issue by Mkbk75** [YanG-1989/m3u#130]
支持的两个球队都在中甲 如果可以的话 麻烦大佬加一下呗

**Comment by YanG-1989** [comment]
> 支持的两个球队都在中甲 如果可以的话 麻烦大佬加一下呗

好吧..中甲居然也有人看。晚点给你加

**Comment by Mkbk75** [comment]
> > 支持的两个球队都在中甲 如果可以的话 麻烦大佬加一下呗
> 
> 好吧..中甲居然也有人看。晚点给你加

呜呜 小城市 踢不上中超

**Comment by YanG-1989** [comment]
> > > 支持的两个球队都在中甲 如果可以的话 麻烦大佬加一下呗
> 
> > 
> 
> > 好吧..中甲居然也有人看。晚点给你加
> 
> 
> 
> 呜呜 小城市 踢不上中超

给你加了..

**Comment by Mkbk75** [comment]
> > > > 支持的两个球队都在中甲 如果可以的话 麻烦大佬加一下呗
> > 
> > 
> > > 
> > 
> > 
> > > 好吧..中甲居然也有人看。晚点给你加
> > 
> > 
> > 呜呜 小城市 踢不上中超
> 
> 给你加了..

谢谢YanG大佬！
