### ISSUE TITLE
有交流频道吗？

### ISSUE THREAD

**Issue by Foza-wechat** [YanG-1989/m3u#138]
大爱作者

**Comment by YanG-1989** [comment]
没有...不想搞这东西🤣
但是你可以来aptv群找到我..

开群太多乱七八糟的事情了...

**Comment by Foza-wechat** [comment]
希望添加个明珠台 并且带字幕。 给小孩巩固粤语

**Comment by Foza-wechat** [comment]
> 没有...不想搞这件事🤣 但是你可以来aptv群找到我..
> 
> 太多乱七八糟的事情了……

希望添加一个明珠台并带字幕。 给孩子巩固粤语

**Comment by Foza-wechat** [comment]
> 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> 
> 开群太多乱七八糟的事情了...
翡翠台的字幕会有个黑色框 能透明吗

**Comment by Foza-wechat** [comment]
> 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> 
> 开群太多乱七八糟的事情了...

希望添加一个星空台

**Comment by YanG-1989** [comment]
> > 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> 
> > 
> 
> > 开群太多乱七八糟的事情了...
> 
> 
> 
> 希望添加一个星空台 

不知道哪里有...

**Comment by Foza-wechat** [comment]
> > > 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> > 
> > 
> > > 
> > 
> > 
> > > 开群太多乱七八糟的事情了...
> > 
> > 
> > 希望添加一个星空台
> 
> 不知道哪里有...

今日影视APP里面有星空台

**Comment by YanG-1989** [comment]
> > > > 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 开群太多乱七八糟的事情了...
> 
> > > 
> 
> > > 
> 
> > > 希望添加一个星空台
> 
> > 
> 
> > 不知道哪里有...
> 
> 
> 
> 今日影视APP里面有星空台


没办法..那你去看今日

**Comment by Foza-wechat** [comment]
> > > > > 没有...不想搞这东西🤣 但是你可以来aptv群找到我..
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 开群太多乱七八糟的事情了...
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 希望添加一个星空台
> > 
> > 
> > > 
> > 
> > 
> > > 不知道哪里有...
> > 
> > 
> > 今日影视APP里面有星空台
> 
> 没办法..那你去看今日

去爬出来 哈哈

**Comment by YanG-1989** [comment]
GitHub 本来就写了..
