### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by fengchenquye** [YanG-1989/m3u#140]
能不能把虎牙娱乐里的四驱兄弟挪到虎牙影视里？

**Comment by YanG-1989** [comment]
> 能不能把虎牙娱乐里的四驱兄弟挪到虎牙影视里？ 

晚上我回去帮你挪一下...

**Comment by fengchenquye** [comment]
> > 能不能把虎牙娱乐里的四驱兄弟挪到虎牙影视里？
> 
> 晚上我回去帮你挪一下...

大佬，yy娱乐里的国产大片电影，不知道谁长传错分类了，没传影视分类里

**Comment by YanG-1989** [comment]
> > > 能不能把虎牙娱乐里的四驱兄弟挪到虎牙影视里？
> 
> > 
> 
> > 晚上我回去帮你挪一下...
> 
> 
> 
> 大佬，yy娱乐里的国产大片电影，不知道谁长传错分类了，没传影视分类里 

改了
