### ISSUE TITLE
AKTV列表更新，现在有56个台

### ISSUE THREAD

**Issue by ashsteins** [YanG-1989/m3u#141]
AKTV列表更新，现在有56个台

现在gather有30个左右

**Comment by huihuimoto** [comment]
这次更新的源感觉这么多都用不了，或者是速度特别慢，卡。

**Comment by YanG-1989** [comment]
> 这次更新的源感觉这么多都用不了，或者是速度特别慢，卡。

v6 目前只有移动好一点...
黑龙江已经挂了...

**Comment by YanG-1989** [comment]
> AKTV列表更新，现在有56个台
> 
> 
> 
> 现在gather有30个左右

我加了36个..不着急其他的也没啥好看的
你直接看他的还不是一样...

**Comment by cwl530** [comment]
大佬体育直播.       咪咕NBA 怎么没了

**Comment by YanG-1989** [comment]
> 大佬体育直播. 咪咕NBA 怎么没了

大哥都没比赛..哪里来的NBA啊....
今天怎么那么多人问我这个问题?
有比赛过了12点就自动刷新的..

**Comment by cwl530** [comment]
> > 大佬体育直播. 咪咕NBA 怎么没了
> 
> 大哥都没比赛..哪里来的NBA啊.... 今天怎么那么多人问我这个问题? 自己都不看比赛的吗? 有比赛过了12点就自动刷新的..

懂了，☺☺☺
