### ISSUE TITLE
家里网络可以看，但是只能看一下就丢失链接

### ISSUE THREAD

**Issue by gh279760559** [YanG-1989/m3u#145]
如题，上上周刚使用，刚开始的时候没有任何问题，结果这周就出现了刚打开的时候能播放，但是过了几分钟的样子就开始断断续续，之后就是连接超时了，应该和app，网络没有关系，因为正如前面提到的，之前播放没有任何问题

**Comment by YanG-1989** [comment]
建议看下置顶吧...
应该是ip跳了的缘故

**Comment by gh279760559** [comment]
> 建议看下置顶吧... 应该是ip跳了的缘故

是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...

**Comment by YanG-1989** [comment]
> > 建议看下置顶吧... 应该是ip跳了的缘故
> 
> 
> 
> 是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...

不是局域网..
最多也就刷新几次而已..
本地ip 跳来跳去就几个

**Comment by gh279760559** [comment]
> > > 建议看下置顶吧... 应该是ip跳了的缘故
> > 
> > 
> > 是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...
> 
> 不是局域网.. 最多也就刷新几次而已.. 本地ip 跳来跳去就几个

那这个ip跳了的缘故请问是什么问题,能否帮忙解决?

**Comment by YanG-1989** [comment]
> > > > 建议看下置顶吧... 应该是ip跳了的缘故
> 
> > > 
> 
> > > 
> 
> > > 是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...
> 
> > 
> 
> > 不是局域网.. 最多也就刷新几次而已.. 本地ip 跳来跳去就几个
> 
> 
> 
> 那这个ip跳了的缘故请问是什么问题,能否帮忙解决?

刷新订阅..最简单方便了
其他方法 固定到一个节点，你估计也不会...

**Comment by aries1998** [comment]
我这边看soop直播也有一样的问题，打开直播没问题，只要看个大概8,9分钟，就开始断流无法播放了，重新打开直播就又ok了，非常的有规律。 soop确认过流量走的是自建vps，应该没有跳ip的问题。

有没有可能更新签名之类的请求间隔太长，导致拿到的流地址失效？

**Comment by YanG-1989** [comment]
> 我这边看soop直播也有一样的问题，打开直播没问题，只要看个大概8,9分钟，就开始断流无法播放了，重新打开直播就又ok了，非常的有规律。 soop确认过流量走的是自建vps，应该没有跳ip的问题。
> 
> 
> 
> 有没有可能更新签名之类的请求间隔太长，导致拿到的流地址失效？
> 
> 

Live 我没限制ip...
可能是脚本问题或者播放器问题..
我下次去测试看看..

**Comment by aries1998** [comment]
> > 我这边看soop直播也有一样的问题，打开直播没问题，只要看个大概8,9分钟，就开始断流无法播放了，重新打开直播就又ok了，非常的有规律。 soop确认过流量走的是自建vps，应该没有跳ip的问题。
> > 有没有可能更新签名之类的请求间隔太长，导致拿到的流地址失效？
> 
> Live 我没限制ip... 可能是脚本问题或者播放器问题.. 我下次去测试看看..

试了下ok影视（电视版，手机版），ott手机版，vlc手机版，都会这样。

**Comment by gh279760559** [comment]
> > > > > 建议看下置顶吧... 应该是ip跳了的缘故
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...
> > 
> > > 
> > 
> > > 不是局域网.. 最多也就刷新几次而已.. 本地ip 跳来跳去就几个
> > 
> > 
> > 
> > 那这个ip跳了的缘故请问是什么问题,能否帮忙解决?
> 
> 刷新订阅..最简单方便了
> 其他方法 固定到一个节点，你估计也不会...
> 

没有使用机场vpn等，是直连连接依然存在上述情况

**Comment by YanG-1989** [comment]
> > > 我这边看soop直播也有一样的问题，打开直播没问题，只要看个大概8,9分钟，就开始断流无法播放了，重新打开直播就又ok了，非常的有规律。 soop确认过流量走的是自建vps，应该没有跳ip的问题。
> 
> > > 有没有可能更新签名之类的请求间隔太长，导致拿到的流地址失效？
> 
> > 
> 
> > Live 我没限制ip... 可能是脚本问题或者播放器问题.. 我下次去测试看看..
> 
> 
> 
> 试了下ok影视（电视版，手机版），ott手机版，vlc手机版，都会这样。

那可能脚本问题吧..我还没长时间测试过

**Comment by YanG-1989** [comment]
> > > > > > 建议看下置顶吧... 应该是ip跳了的缘故
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > 是指的局域网ip跳的原因吗?不应该吧,本地的话怎么会播放几分钟以后ip自动跳...
> > > 
> > > > 
> > > 
> > > > 不是局域网.. 最多也就刷新几次而已.. 本地ip 跳来跳去就几个
> > > 
> > > 
> > > 
> > > 那这个ip跳了的缘故请问是什么问题,能否帮忙解决?
> > 
> > 刷新订阅..最简单方便了
> > 其他方法 固定到一个节点，你估计也不会...
> > 
> 
> 没有使用机场vpn等，是直连连接依然存在上述情况

运营商ip乱跳我也没办法...
方法已经告诉你了...
置顶也有写解决方法..
