### ISSUE TITLE
【清晰度问题】目前都是1080p

### ISSUE THREAD

**Issue by Popxie** [YanG-1989/m3u#146]
请问一下直播源都是默认1080p的嘛？有没有更高的分辨率的呀？我的神！

**Comment by YanG-1989** [comment]
> 请问一下直播源都是默认1080p的嘛？有没有更高的分辨率的呀？我的神！

没有..

**Comment by Popxie** [comment]
大神还没睡啊

**Comment by YanG-1989** [comment]
> 大神还没睡啊 

没有准备睡觉了..就看一眼

**Comment by Popxie** [comment]
> > 大神还没睡啊
> 
> 没有准备睡觉了..就看一眼
还在研究，感谢大神的分享 爱了爱了，
