### ISSUE TITLE
【存在无法播放直播源·能过滤一下吗】

### ISSUE THREAD

**Issue by Popxie** [YanG-1989/m3u#147]
我在Jellyfin里用的大佬那个最全的直播源1630个，发现好多都提示错误无法播放，能不能过滤掉不能使用的直播源啊？

另外在Jellyfin里只能这么一页一页翻看查找吗？😂

**Comment by YanG-1989** [comment]
> 我在Jellyfin里用的大佬那个最全的直播源1630个，发现好多都提示错误无法播放，能不能过滤掉不能使用的直播源啊？
> 
> 
> 
> 另外在Jellyfin里只能这么一页一页翻看查找吗？😂

用iptv的软件呗..
我里面95% 以上是正常的..
目前只有台湾里面的部分坏了
