### ISSUE TITLE
請問是否支持yuki-iptv

### ISSUE THREAD

**Issue by SingKS8** [YanG-1989/m3u#148]
最近一週發現 [yuki-iptv ](https://codeberg.org/liya/yuki-iptv) 無法fetching playlist，是否收緊了UA的校驗。
我是Linux用户，前面一些推薦iptv都無相應版本，所以client 用得有點偏，For Linux，這款iptv功能相對是齊全一些，就是fetching playlist時候無法指定UA。

**Comment by SingKS8** [comment]
它首先用我配置的UA，但看它fetching時候有些奇怪的retry，今天發現又成功fetching playlist，可能就是這個client 問題。

**Comment by YanG-1989** [comment]
> 它首先用我配置的UA，但看它fetching時候有些奇怪的retry，今天發現又成功fetching playlist，可能就是這個client 問題。

应该是你刷新订阅频繁了，ip进黑名单了。
我昨天把黑名单ip清空了...
