### ISSUE TITLE
大佬求助，AKTV的源看着看着显示长时间占用等

### ISSUE THREAD

**Issue by lucasyippp** [YanG-1989/m3u#152]
大佬求助，AKTV的源看着看着显示长时间占用等。安卓电视平台 软件是Tivimate正版。

**Comment by YanG-1989** [comment]
.....这个和我没关系!!! AKTV的问题 我单纯加进来而已

**Comment by lucasyippp** [comment]
> .....这个和我没关系!!! AKTV的问题 我单纯加进来而已

好的，谢谢大佬
