### ISSUE TITLE
为什么aptv最近经常显示“该地址返回的了无效的内容，请检查网络或地址内容”

### ISSUE THREAD

**Issue by YuanGAO0220** [YanG-1989/m3u#156]
偶尔可以成功，但经常无效。

tivimate直接是看不了，频道都出不来

**Comment by YanG-1989** [comment]
> 偶尔可以成功，但经常无效。
> 
> 
> 
> tivimate直接是看不了，频道都出不来

看置顶..
aptv 恢复默认ua
不应该出现这个情况

**Comment by maycyc** [comment]
> > 有时可以成功，但经常无效。
> > tivimate直接是看不了，频道都出不来
> 
> 看置顶.. aptv 恢复默认ua 不应该出现这种情况

的确是恢复默认UA就好了，之前一直是无效地址。
但添加APTV其它直接添加的直播源没有问题。
原设置UA `**AptvPlayer/1.2.12 Mozilla(iPhone)**`无法添加

**Comment by YanG-1989** [comment]
> > > 有时可以成功，但经常无效。
> 
> > > tivimate直接是看不了，频道都出不来
> 
> > 
> 
> > 看置顶.. aptv 恢复默认ua 不应该出现这种情况
> 
> 
> 
> 的确是恢复默认UA就好了，之前一直是无效地址。
> 
> 但添加APTV其它直接添加的直播源没有问题。
> 
> 原设置UA  **AptvPlayer/1.2.12 Mozilla(iPhone)** 无法添加
> 
> 

你这个ua带浏览器了..我的订阅屏蔽了..
你想兼容其他订阅，我是建议你订阅单独设置ua

**Comment by YuanGAO0220** [comment]
我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。

**Comment by YanG-1989** [comment]
> 我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。

如果直连订阅不成功...
加节点吧..
我都怀疑是不是你的ip都给拉黑了

**Comment by YuanGAO0220** [comment]
> > 我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。
> 
> 如果直连订阅不成功... 加节点吧.. 我都怀疑是不是你的ip都给拉黑了

怎么加节点啊？能不能帮忙查一下ip有没有被拉黑呢？

**Comment by YanG-1989** [comment]
> > > 我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。
> 
> > 
> 
> > 如果直连订阅不成功... 加节点吧.. 我都怀疑是不是你的ip都给拉黑了
> 
> 
> 
> 怎么加节点啊？能不能帮忙查一下ip有没有被拉黑呢？

发前三段...就是挂代理啊囧

**Comment by YuanGAO0220** [comment]
> > > > 我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。
> > 
> > 
> > > 
> > 
> > 
> > > 如果直连订阅不成功... 加节点吧.. 我都怀疑是不是你的ip都给拉黑了
> > 
> > 
> > 怎么加节点啊？能不能帮忙查一下ip有没有被拉黑呢？
> 
> 发前三段...就是挂代理啊囧

76.126.31

**Comment by YanG-1989** [comment]
> > > > > 我没有用任何ua，都是默认设置。之前一直是能用的，最近两周开始，每天只有很短时间段可以订阅成功。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 如果直连订阅不成功... 加节点吧.. 我都怀疑是不是你的ip都给拉黑了
> 
> > > 
> 
> > > 
> 
> > > 怎么加节点啊？能不能帮忙查一下ip有没有被拉黑呢？
> 
> > 
> 
> > 发前三段...就是挂代理啊囧
> 
> 
> 
> 76.126.31

应该ok了..

**Comment by YuanGAO0220** [comment]
原来是进黑名单了，奇怪，我应该没干啥啊。

anyway 感谢

**Comment by YanG-1989** [comment]
> 原来是进黑名单了，奇怪，我应该没干啥啊。
> 
> 
> 
> anyway 感谢

频繁刷新了..一般很难触发
