### ISSUE TITLE
央视和地方的ipv6都失效了？

### ISSUE THREAD

**Issue by hiyuxiang** [YanG-1989/m3u#157]
央视和地方的ipv6都失效了？

**Comment by bug417** [comment]
> 央视和地方的ipv6都失效了？

+1，目前看似乎还没恢复

**Comment by YanG-1989** [comment]
换的海南v6 不好使...
去试下 范明明的甘肃v6

--------  计划  ----------

晚上我给gather 换百事通v6..
GitHub 保留 海南v6

-------------------------

**Comment by Currylce** [comment]
我用ok影视+上海电信，目前还是不能看所有IPV6的源，显示播放地址加载失败。

**Comment by YanG-1989** [comment]
> 我用ok影视+上海电信，目前还是不能看所有IPV6的源，显示播放地址加载失败。

看v4吧...
目前活着的v6 对其他两家网络都不友好
