### ISSUE TITLE
iptv pro怎么能够订阅成功？谢谢！

### ISSUE THREAD

**Issue by SherwinWg** [YanG-1989/m3u#159]
现在是iptv pro 8.2.4版本，订阅不成功有几觉办法吗？

**Comment by YanG-1989** [comment]
> 现在是iptv pro 8.2.4版本，订阅不成功有几觉办法吗？

改ua..
置顶说明仔细看看..

真不行抓ua 给我..

**Comment by SherwinWg** [comment]
置顶没有找到，我用小黄鸟抓了下，是这个
Dalvik/2.1.0

**Comment by YanG-1989** [comment]
换成 Televizo「手机端」 ..别折腾了
