### ISSUE TITLE
是不是不能撸CF了, 感觉网速掉的厉害

### ISSUE THREAD

**Issue by mipaers** [YanG-1989/m3u#161]

**Comment by YanG-1989** [comment]
> 

没怎么测试..我都用节点的😂

**Comment by kitkw** [comment]
> > 
> 
> 没怎么测试..我都用节点的😂

刚开始  速度还不错 2-3m/s   但一阵间就  只有1-200K 。太卡看不了 为什么？？？要用节点睇？？但我使用节点后是直接打不开的，用的是potplayer

**Comment by abc11159** [comment]
看电视还需要节点？

**Comment by kitkw** [comment]
需要节点唔紧要。关键是只能睇一阵，很快就掉速到不能睇。。。。。 如（翡翠台） http://aktv.top/AKTV/live/aktv/null/AKTV.m3u8      直链能打开但掉速  ，使用代理直接打开报错

**Comment by abc11159** [comment]
没出现过你那样的情况

**Comment by kitkw** [comment]
> 没出现过你那样的情况

内地台好像没这状况（IPV6）  aktv 这个域名的好像会掉速

**Comment by YanG-1989** [comment]
> 需要节点唔紧要。关键是只能睇一阵，很快就掉速到不能睇。。。。。 如（翡翠台） http://aktv.top/AKTV/live/aktv/null/AKTV.m3u8      直链能打开但掉速  ，使用代理直接打开报错
> 
> ![image](https://github.com/user-attachments/assets/5204a4e4-ccd1-46da-841b-90182f83d1fb)
> 
> 

我的稳定一些...aktv 经常发神经

**Comment by kitkw** [comment]
> > 需要节点唔紧要。关键是只能睇一阵，很快就掉速到不能睇。。。。。 如（翡翠台） http://aktv.top/AKTV/live/aktv/null/AKTV.m3u8      直链能打开但掉速  ，使用代理直接打开报错
> > ![image](https://private-user-images.githubusercontent.com/31963066/397749236-5204a4e4-ccd1-46da-841b-90182f83d1fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3Nzc3MTUsIm5iZiI6MTczNDc3NzQxNSwicGF0aCI6Ii8zMTk2MzA2Ni8zOTc3NDkyMzYtNTIwNGE0ZTQtY2NkMS00NmRhLTg0MWItOTAxODJmODNkMWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEwMzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOWZmZWIwODQ5YmM0ODNiMTQxZDZjOGU4YTUwMDk1OTJjY2RmZDg4Mzg0NmNiMzZmYTFjOWMyNzIyNDI4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I9m7fj7v-jvvzwzc5oRVX9SIPQxmJycmi5STXOZrp0I)
> 
> 我的稳定一些...aktv 经常发神经

ill 那个是你的？

**Comment by YanG-1989** [comment]
> > > 需要节点唔紧要。关键是只能睇一阵，很快就掉速到不能睇。。。。。 如（翡翠台） http://aktv.top/AKTV/live/aktv/null/AKTV.m3u8      直链能打开但掉速  ，使用代理直接打开报错
> 
> > > ![image](https://private-user-images.githubusercontent.com/31963066/397749236-5204a4e4-ccd1-46da-841b-90182f83d1fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3Nzc3MTUsIm5iZiI6MTczNDc3NzQxNSwicGF0aCI6Ii8zMTk2MzA2Ni8zOTc3NDkyMzYtNTIwNGE0ZTQtY2NkMS00NmRhLTg0MWItOTAxODJmODNkMWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEwMzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOWZmZWIwODQ5YmM0ODNiMTQxZDZjOGU4YTUwMDk1OTJjY2RmZDg4Mzg0NmNiMzZmYTFjOWMyNzIyNDI4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I9m7fj7v-jvvzwzc5oRVX9SIPQxmJycmi5STXOZrp0I)
> 
> > 
> 
> > 我的稳定一些...aktv 经常发神经
> 
> 
> 
> ill 那个是你的？

不然是谁的？GitHub的很明白吧...
