### ISSUE TITLE
订阅地址怎么用的？

### ISSUE THREAD

**Issue by 252162875** [YanG-1989/m3u#163]
yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～

**Comment by YanG-1989** [comment]
> yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～
> 
> 

这个是网站...去网站里面拿订阅

**Comment by 252162875** [comment]
谢谢大佬回复，https://tv.iill.top/m3u/Gather,我意思拿到的这个订阅地址在软件里面怎么订阅，我用tivimate、mytv、iptv pro都没见有地方订阅～可能是我不会吧

**Comment by 252162875** [comment]
> > yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～
> 
> 这个是网站...去网站里面拿订阅

谢谢大佬回复，[https://tv.iill.top/m3u/Gather,我意思拿到的这个订阅地址在软件里面怎么订阅，我用tivimate、mytv、iptv](https://tv.iill.top/m3u/Gather,%E6%88%91%E6%84%8F%E6%80%9D%E6%8B%BF%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E8%AE%A2%E9%98%85%E5%9C%B0%E5%9D%80%E5%9C%A8%E8%BD%AF%E4%BB%B6%E9%87%8C%E9%9D%A2%E6%80%8E%E4%B9%88%E8%AE%A2%E9%98%85%EF%BC%8C%E6%88%91%E7%94%A8tivimate%E3%80%81mytv%E3%80%81iptv) pro都没见有地方订阅～可能是我不会吧

**Comment by cnbeta2023** [comment]
12月18号更新的内容怎么不在M3U文件里面，没有香港源

**Comment by cnbeta2023** [comment]
12月18号更新的内容怎么不在M3U文件里面，没有香港源

**Comment by YanG-1989** [comment]
> 12月18号更新的内容怎么不在M3U文件里面，没有香港源

不是加了一点点了吗？
国际 和 港台 这两个分组 
还有台湾  都加频道了

**Comment by YanG-1989** [comment]
> > > yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～
> 
> > 
> 
> > 这个是网站...去网站里面拿订阅
> 
> 
> 
> 谢谢大佬回复，[https://tv.iill.top/m3u/Gather,我意思拿到的这个订阅地址在软件里面怎么订阅，我用tivimate、mytv、iptv](https://tv.iill.top/m3u/Gather,%E6%88%91%E6%84%8F%E6%80%9D%E6%8B%BF%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E8%AE%A2%E9%98%85%E5%9C%B0%E5%9D%80%E5%9C%A8%E8%BD%AF%E4%BB%B6%E9%87%8C%E9%9D%A2%E6%80%8E%E4%B9%88%E8%AE%A2%E9%98%85%EF%BC%8C%E6%88%91%E7%94%A8tivimate%E3%80%81mytv%E3%80%81iptv) pro都没见有地方订阅～可能是我不会吧

输入地址不就行了吗？....

**Comment by 252162875** [comment]
> > > > yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～
> > 
> > 
> > > 
> > 
> > 
> > > 这个是网站...去网站里面拿订阅
> > 
> > 
> > 谢谢大佬回复，[https://tv.iill.top/m3u/Gather,我意思拿到的这个订阅地址在软件里面怎么订阅，我用tivimate、mytv、iptv](https://tv.iill.top/m3u/Gather,%E6%88%91%E6%84%8F%E6%80%9D%E6%8B%BF%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E8%AE%A2%E9%98%85%E5%9C%B0%E5%9D%80%E5%9C%A8%E8%BD%AF%E4%BB%B6%E9%87%8C%E9%9D%A2%E6%80%8E%E4%B9%88%E8%AE%A2%E9%98%85%EF%BC%8C%E6%88%91%E7%94%A8tivimate%E3%80%81mytv%E3%80%81iptv) pro都没见有地方订阅～可能是我不会吧
> 
> 输入地址不就行了吗？....

呃，我傻逼了，直接和.M3U一样用就行了～

**Comment by YanG-1989** [comment]
> > > > > yang-1989.eu.org这个订阅地址怎么使用的？麻烦有知道的大哥教一下～
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 这个是网站...去网站里面拿订阅
> 
> > > 
> 
> > > 
> 
> > > 谢谢大佬回复，[https://tv.iill.top/m3u/Gather,我意思拿到的这个订阅地址在软件里面怎么订阅，我用tivimate、mytv、iptv](https://tv.iill.top/m3u/Gather,%E6%88%91%E6%84%8F%E6%80%9D%E6%8B%BF%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E8%AE%A2%E9%98%85%E5%9C%B0%E5%9D%80%E5%9C%A8%E8%BD%AF%E4%BB%B6%E9%87%8C%E9%9D%A2%E6%80%8E%E4%B9%88%E8%AE%A2%E9%98%85%EF%BC%8C%E6%88%91%E7%94%A8tivimate%E3%80%81mytv%E3%80%81iptv) pro都没见有地方订阅～可能是我不会吧
> 
> > 
> 
> > 输入地址不就行了吗？....
> 
> 
> 
> 呃，我傻逼了，直接和.M3U一样用就行了～

你想的太复杂了...
