### ISSUE TITLE
你好，问下咪咕的源有网络限制吗

### ISSUE THREAD

**Issue by noob1993129** [YanG-1989/m3u#165]
打开咪咕的ipv4源打不开，天津联通网络

**Comment by noob1993129** [comment]
咪咕官方订阅是哪个大佬，没找到

**Comment by YanG-1989** [comment]
> 咪咕官方订阅是哪个大佬，没找到

官方哪里来的订阅...
我的意思看到都是官方的源..

**Comment by noob1993129** [comment]
> > 咪咕官方订阅是哪个大佬，没找到
> 
> 官方哪里来的订阅... 我的意思看到都是官方的源..

早休息吧大佬，我自己在研究研究，播了几个都播不了
![image](https://github.com/user-attachments/assets/2991459c-f738-4f5f-8ff0-f701d58491cc)

**Comment by YanG-1989** [comment]
> > > 咪咕官方订阅是哪个大佬，没找到
> 
> > 
> 
> > 官方哪里来的订阅... 我的意思看到都是官方的源..
> 
> 
> 
> 早休息吧大佬，我自己在研究研究，播了几个都播不了
> 
> ![image](https://github.com/user-attachments/assets/2991459c-f738-4f5f-8ff0-f701d58491cc)
> 
> 

有ua和ip限制...你看看问答区置顶吧..
我睡觉去了
