### ISSUE TITLE
请问adult频道怎么没有了，哪位大佬提供下神秘链接

### ISSUE THREAD

**Issue by qylgy530** [YanG-1989/m3u#167]
请问adult频道怎么没有了，哪位大佬提供下神秘链接，手机清空了，找不到链接了，谢谢

**Comment by YanG-1989** [comment]
> 请问adult频道怎么没有了，哪位大佬提供下神秘链接，手机清空了，找不到链接了，谢谢

我都没更新了...把Live或者其他换成Adult 就行
