### ISSUE TITLE
IPV6的看不了，之前都可以正常看的

### ISSUE THREAD

**Issue by yangbe** [YanG-1989/m3u#19]

**Comment by YanG-1989** [comment]
你网络问题或者没更新，除了个别的失效了。我还没替换。其他都正常！

**Comment by yangbe** [comment]
## NewTV这些好像都看不了
<img width="808" alt="image" src="https://github.com/YanG-1989/m3u/assets/9880101/754143dc-b36f-478e-a830-536dba308172">
