### ISSUE TITLE
请求大佬加几个主播~

### ISSUE THREAD

**Issue by Roger-1987** [YanG-1989/m3u#2]
跪求大佬加上芜湖大司马丶（60618）和一条小团团OvO（2222）么？
麻烦大佬了！~
PS：括号里面是房间号，这两个人都某鱼的

**Comment by Roger-1987** [comment]
括号里面是房间号~

**Comment by YanG-1989** [comment]
我也就是搬运工！增加了，你有空试下看看能不能看 ！

**Comment by Roger-1987** [comment]
大佬，多谢回复！~
我发现芜湖大司马丶的房间号我打错了...少打了个1
应该是606118...
对不起大佬，是我二货了...
一条小团团OvO没有问题可以正常观看
还有大佬能求你再加一个昔恩小姐姐（6301433）么？

**Comment by zwgh1725** [comment]
大佬可以几个斗鱼余小C真的很强1126960，微笑16101，虎牙霸哥189201 0.0
