### ISSUE TITLE
使用小问题汇集

### ISSUE THREAD

**Issue by yangbe** [YanG-1989/m3u#20]
# 20230603 

- [x] 发现央视、卫视、SiTV等倒了一大片

# 20230527   

- [x]  CCTV.IPV6的频道在回看时都跳转到 CCTV1

- [x] CCTV 5 画面比例不是16:9 或 16:10，应该是4:3，被压了宽度

- [x] NewTV 古装剧场、海外剧场 不能播放

- [ ] 希望后续可以加一些广东那边的地方频道

**Comment by YanG-1989** [comment]
你先更新下订阅。
CCTV我回看是正常的，你告诉我，是那个CCTV，我去试下。
CCTV5 我已经替换了，应该已经正常。
古装和海外剧场，是失效了。我没删除而已
广东地方台 有空我去找找看

**Comment by peakzheng1112** [comment]
hi，能不能把山东电视台的地方频道放到IPv6,最好有山东体育频道！腾讯体育能否搞到直播源？



郑振锋


------------------ 原始邮件 ------------------
发件人: YanG-1989 ***@***.***&gt;
发送时间: 2023年5月29日 21:23
收件人: YanG-1989/m3u ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [YanG-1989/m3u] 使用小问题汇集 (Issue #20)





 
你先更新下订阅。
 CCTV我回看是正常的，你告诉我，是那个CCTV，我去试下。
 CCTV5 我已经替换了，应该已经正常。
 古装和海外剧场，是失效了。我没删除而已
 广东地方台 有空我去找找看

**Comment by YanG-1989** [comment]
没有山东的 ipv6，腾讯你去网页上找临时的吧。

**Comment by yangbe** [comment]
<img width="1917" alt="SCR-20230603-hka" src="https://github.com/YanG-1989/m3u/assets/9880101/968944e5-99a6-4ad4-8f0d-717cb7a01f84">
<img width="1917" alt="SCR-20230603-hk1" src="https://github.com/YanG-1989/m3u/assets/9880101/823bba12-d590-4655-b20c-a5da2324973d">
![SCR-20230603-hlc](https://github.com/YanG-1989/m3u/assets/9880101/8c9cb023-c1c1-4e6a-ad93-23571496ca71)

**Comment by tt88gz** [comment]
6-6日反馈

广东电信网络，IPTVPro软件
1. IPV6数字，凤凰资讯和凤凰中文台标顺序颠倒，凤凰香港无信号。
2. IPV6央视，1-17频道只有5正常，风云数字各频道正常。
3. IPV6卫视，江苏、北京、广西通，大部分卫视转圈。

**Comment by yangbe** [comment]
关闭了，这几个月都没有什么问题
