### ISSUE TITLE
好像adult的直播都不能看了.

### ISSUE THREAD

**Issue by HakkaDe** [YanG-1989/m3u#25]
大佬能修复一下吗

**Comment by YanG-1989** [comment]
没有延迟，代表人家没直播！有延迟看不了，应该是开了收费模式。

**Comment by OmegaXF** [comment]
怎么批量加入potplayer

**Comment by YanG-1989** [comment]
> 怎么批量加入potplayer

下载到本地，加呗。电脑的我没怎么用不清楚

**Comment by HakkaDe** [comment]
大佬能添加多点国内那些传媒的吗，谢谢啦

**Comment by YanG-1989** [comment]
> 大佬能添加多点国内那些传媒的吗，谢谢啦

偶尔会更新....
佛系,前两天更新了一点你可以去看看。

**Comment by kwong900** [comment]
大佬加点韩国的吧🥹

**Comment by tototuo** [comment]
douyu的好像看不了了

**Comment by YanG-1989** [comment]
> 大佬加点韩国的吧🥹

韩国没什么接触到...都是小短片吧

**Comment by kwong900** [comment]
> > 大佬加点韩国的吧🥹
> 
> 韩国没什么接触到...都是小短片吧

韩国三级好看的，有剧情
