### ISSUE TITLE
直播源中后缀名是m3u8?的TiviMate无法播放怎么回事？

### ISSUE THREAD

**Issue by sdhzxq** [YanG-1989/m3u#28]
在APPLETV上用APTV播放正常。在安卓电视上用TiviMate播放，有一部分频道播放不了，打开直播源发现无法播放的频道后缀名都是m3u8?，这是怎么回事啊？用IPTVPRO也不行

**Comment by YanG-1989** [comment]
> 在APPLETV上用APTV播放正常。在安卓电视上用TiviMate播放，有一部分频道播放不了，打开直播源发现无法播放的频道后缀名都是m3u8?，这是怎么回事啊？用IPTVPRO也不行

aptv可能做了识别，tivimate把带？都算进去了 算一种其他格式。我有空去吧这个？批量取消掉应该就行了

**Comment by HurryYU** [comment]
我尝试去掉了`?`后还是不行
以CCTV1这个地址举例,`http://[2409:8087:1e03:21::42]:6610/cms001/ch00000090990000001022/index.m3u8`如果去掉了`?`,在浏览器中直接报400
如果加上`?`,会先返回一个302重定向到类似`http://[2409:8087:1e03:21::42]:6610/cms001/ch00000090990000001022/index.m3u8?IASHttpSessionId=OTT853720231121024417726351`地址,该地址则可以正常获取`m3u8`文件

所以我感觉是tivimate没有处理302 导致无法播放这类源

**Comment by HurryYU** [comment]
破案了
**tivimate可以处理302重定向,但是URL地址一定要规范**
现在知道的是,带`?`号的那些源应该都是需要经过302的,不带`?`或者说地址后面不跟上点字符,就会直接400
但是类似`http://www.xxx.com/a?`并不是标准的URL传参形式,浏览器能处理,但是tivimate处理不了
所以只需要把那些带有`?`号的地址,改为标准的URL传参形式,tivimate就能识别了

**Comment by YanG-1989** [comment]
> 破案了
> 
> **tivimate可以处理302重定向,但是URL地址一定要规范**
> 
> 现在知道的是,带`?`号的那些源应该都是需要经过302的,不带`?`或者说地址后面不跟上点字符,就会直接400
> 
> 但是类似`http://www.xxx.com/a?`并不是标准的URL传参形式,浏览器能处理,但是tivimate处理不了
> 
> 所以只需要把那些带有`?`号的地址,改为标准的URL传参形式,tivimate就能识别了
> 
> 例如CCTV1改为`http://[2409:8087:1e03:21::42]:6610/cms001/ch00000090990000001022/index.m3u8?user=hurryyu`即可正常播放




那么高大上吗！没研究过..因为我没入正版，我用的是影视tv的壳...你解决了就好了.
