### ISSUE TITLE
问下，联通的网络以前可以播放，现在播放不了了。如何解决谢谢

### ISSUE THREAD

**Issue by noob1993129** [YanG-1989/m3u#33]
http://gslbserv.itv.cmvideo.cn:80/3000000010000017389/index.m3u8?channel-id=FifastbLive&Contentid=3000000010000017389&livemode=1&stbId=3

联通的网络无法访问 咪咕 ipv4的链接，问下作者如何解决

**Comment by YanG-1989** [comment]
> http://gslbserv.itv.cmvideo.cn:80/3000000010000017389/index.m3u8?channel-id=FifastbLive&Contentid=3000000010000017389&livemode=1&stbId=3
> 
> 
> 
> 
> 
> 联通的网络无法访问 咪咕 ipv4的链接，问下作者如何解决

没办法....
本来就限制移动的。
建议你用v6的..
