### ISSUE TITLE
Gather里大部分的都看不了，是我的操作方式不对吗？

### ISSUE THREAD

**Issue by thegenway** [YanG-1989/m3u#38]
我是直接复制地址到播放器里播的，Gather里试了好多，只有几个韩国的直播能看，cctv的还有各种卫视的还有咪咕的那些都不行，是还要配置什么东西吗？

不过Adult里的大部分倒是的都能看，嘿嘿

**Comment by MrJdy** [comment]
> > 嘿嘿
> > 写着需要ipv6 分组的都正常
> > ipv4的 不稳定的，懒得维护。
> > Adult 大部分失效了 这几天我要维护一下

大佬 万人血书 请求Adult记得加上台北娜娜（Taipei_nana），还有 桥本香菜（名字没写错，中国的）

**Comment by YanG-1989** [comment]
> > > 嘿嘿
> 
> > > 写着需要ipv6 分组的都正常
> 
> > > ipv4的 不稳定的，懒得维护。
> 
> > > Adult 大部分失效了 这几天我要维护一下
> 
> 
> 
> 大佬 万人血书 请求Adult记得加上台北娜娜（Taipei_nana），还有 桥本香菜（名字没写错，中国的）


娜娜资源好像挺少的，桥本香菜我去看看。最近事情多，adult失效了  我都还没维护呢

**Comment by hathimaioanh** [comment]
Hi @MrJdy , I’ve tried multiple times to add Taipei Nana to the app without success. Could you please share a link to her? Thank you so much!

> > > 嘿嘿
> > > 写着需要ipv6 分组的都正常
> > > ipv4的 不稳定的，懒得维护。
> > > Adult 大部分失效了 这几天我要维护一下
> 
> 大佬 万人血书 请求Adult记得加上台北娜娜（Taipei_nana），还有 桥本香菜（名字没写错，中国的）
