### ISSUE TITLE
adult的很多不能播放了

### ISSUE THREAD

**Issue by zhixuans** [YanG-1989/m3u#4]
adult的很多不能播放了🤣

**Comment by YanG-1989** [comment]
> adult的很多不能播放了🤣

我知道，最近没空整理！等我感冒好了再抽空搞搞

**Comment by zhixuans** [comment]
> > adult的很多不能播放了🤣
> 
> 我知道，最近没空整理！等我感冒好了再抽空搞搞
辛苦了～

**Comment by zhixuans** [comment]
> > adult的很多不能播放了🤣
> 
> 我知道，最近没空整理！等我感冒好了再抽空搞搞

辛苦了～

**Comment by Najix-1999** [comment]
所以它提示服务器未响应不是我网络的问题吗😂，我还以为是因为我网络不对，全局代理局部代理试了半天

**Comment by LiangZhenX** [comment]
玩偶YYDS

**Comment by Najix-1999** [comment]
已收入邮箱。

**Comment by CHUCK198912** [comment]
m3u地址是哪个？这么多地址需要一个一个加吗？

**Comment by Najix-1999** [comment]
已收入邮箱。

**Comment by CHUCK198912** [comment]
这么多地址需要一个一个加吗？
刚刚开始研究，还请指教。

**Comment by YanG-1989** [comment]
> 这么多地址需要一个一个加吗？
> 
> 刚刚开始研究，还请指教。

不是一个一个！囧，点那个 view raw，复制地址就行了。

**Comment by dissaplay** [comment]
大佬，求教一下 在哪里复制地址，研究两天了 没有搞明白，一直 在一条一条的复制进浏览器观看

**Comment by YanG-1989** [comment]
> 大佬，求教一下 在哪里复制地址，研究两天了 没有搞明白，一直 在一条一条的复制进浏览器观看

我已经说的很明白了，当然是弹出来的地址。还看不懂建议百度或者谷歌下...

**Comment by Najix-1999** [comment]
已收入邮箱。
