### ISSUE TITLE
老哥，Gather求更新！父母要喷死我了

### ISSUE THREAD

**Issue by Shawnkurt** [YanG-1989/m3u#40]
上周日中午貌似统一换了地址，大部分都失效了
老哥求更新啊，爸妈就指望着你了
留个二维码我支持一下！

**Comment by ImproveRei0** [comment]
+1 求更新

**Comment by YanG-1989** [comment]
> 上周日中午貌似统一换了地址，大部分都失效了
> 
> 老哥求更新啊，爸妈就指望着你了
> 
> 留个二维码我支持一下！

没更换地址..上海ipv6的失效了
12.31号 我在换成江苏ipv6去吧

**Comment by whhxmwhh** [comment]
感谢您！大佬也。
