### ISSUE TITLE
请问为什么今天重新添加订阅时gather地址解析错误了，用的iPhone的aptv

### ISSUE THREAD

**Issue by passersby666** [YanG-1989/m3u#46]

**Comment by YanG-1989** [comment]
你订阅地址错了把

**Comment by YanG-1989** [comment]
https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u

我的说明里面还写了订阅地址...
现在复制给你，还不行就是你网络问题。

**Comment by passersby666** [comment]
好的，谢谢🙏 昨天是在家aptv可以订阅，电视tivimate解析错误，电脑的potplayer也可以看
