### ISSUE TITLE
今天直播源很卡

### ISSUE THREAD

**Issue by passersby666** [YanG-1989/m3u#47]
昨天弄好了大佬，今天晚上回来发现直播源很卡，是网络原因吗，还是周末用的人多啊

**Comment by YanG-1989** [comment]
> 昨天弄好了大佬，今天晚上回来发现直播源很卡，是网络原因吗，还是周末用的人多啊

你可能是联通的吧？
下次试下其他网络…

**Comment by Shawnkurt** [comment]
卧槽 大佬联通是有啥问题吗，我现在看所有源几乎都卡……

**Comment by YanG-1989** [comment]
> 卧槽 大佬联通是有啥问题吗，我现在看所有源几乎都卡……

你可以用移动和电信的对比下..

**Comment by giroro** [comment]
江苏电信，自5月16日维护后就变得非常卡，无论白天晚上周末还是工作日，跪求大神看看是什么问题

**Comment by YanG-1989** [comment]
> 江苏电信，自5月16日维护后就变得非常卡，无论白天晚上周末还是工作日，跪求大神看看是什么问题

v6我基本上没动过....
你自己用流量测试下就知道了...

**Comment by giroro** [comment]
> > 江苏电信，自5月16日维护后就变得非常卡，无论白天晚上周末还是工作日，跪求大神看看是什么问题
> 
> v6我基本上没动过.... 你自己用流量测试下就知道了...

江苏联通的手机也测试过，情况是一样的，大部分的ipv6频道都非常卡，无法正常观看，ping都是绿色的，但是点进去后只有1秒不到的画面就开始转圈

**Comment by YanG-1989** [comment]
> > > 江苏电信，自5月16日维护后就变得非常卡，无论白天晚上周末还是工作日，跪求大神看看是什么问题
> 
> > 
> 
> > v6我基本上没动过.... 你自己用流量测试下就知道了...
> 
> 
> 
> 江苏联通的手机也测试过，情况是一样的，大部分的ipv6频道都非常卡，无法正常观看，ping都是绿色的，但是点进去后只有1秒不到的画面就开始转圈


联通高峰期就这样..
江苏移动好啊，还有cctv 1.3.5的 4k
