### ISSUE TITLE
源里面一个都播放不了

### ISSUE THREAD

**Issue by gaoqiang328** [YanG-1989/m3u#48]
今天找到了这个源，添加了电视台直播能够正常打开，adult里面一个都打开不了，大佬什么原因，是全部失效了吗，能不能修复一下

**Comment by YanG-1989** [comment]
> 今天找到了这个源，添加了电视台直播能够正常打开，adult里面一个都打开不了，大佬什么原因，是全部失效了吗，能不能修复一下

后面的应该正常吧，好久没注意了。把代理关了试下
