### ISSUE TITLE
虎牙直播源都不能用了

### ISSUE THREAD

**Issue by Yigehaoren8848** [YanG-1989/m3u#50]
虎牙直播源都挂了，作者可以贴一下，虎牙直播源的爬虫代码吗？或者作者在哪里抓包得到的数据，虎牙apo还是网页端

**Comment by YanG-1989** [comment]
> 虎牙直播源都挂了，作者可以贴一下，虎牙直播源的爬虫代码吗？或者作者在哪里抓包得到的数据，虎牙apo还是网页端

我去试了下播放正常！代码是肥羊公开的，你自己找下就有了。

**Comment by zsl-157** [comment]
> > 虎牙直播源都挂了，作者可以贴一下，虎牙直播源的爬虫代码吗？或者作者在哪里抓包得到的数据，虎牙apo还是网页端
> 
> 我去试了下播放正常！代码是肥羊公开的，你自己找下就有了。

可以贴一下肥羊的主页吗？劳烦！

**Comment by zsl-157** [comment]
> > 虎牙直播源都挂了，作者可以贴一下，虎牙直播源的爬虫代码吗？或者作者在哪里抓包得到的数据，虎牙apo还是网页端
> 
> 我去试了下播放正常！代码是肥羊公开的，你自己找下就有了。

https://yang-1989.eu.org/huya/23749096    比如这个链接是访问不了的，好像接口挂了

**Comment by YanG-1989** [comment]
> https://yang-1989.eu.org/huya/23749096    比如这个链接是访问不了的，好像接口挂了

我看正常啊..埋堆堆
可能脚本偶尔解析错误？

**Comment by zsl-157** [comment]
> > https://yang-1989.eu.org/huya/23749096    比如这个链接是访问不了的，好像接口挂了
> 
> 我看正常啊..埋堆堆
> 可能脚本偶尔解析错误？

用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行

**Comment by zsl-157** [comment]
> > > https://yang-1989.eu.org/huya/23749096    比如这个链接是访问不了的，好像接口挂了
> > 
> > 我看正常啊..埋堆堆
> > 可能脚本偶尔解析错误？
> 
> 用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行

前两天用同样的浏览器还正常，现在链接都打不开了，感觉可能脚本有时候可能确实有问题

**Comment by YanG-1989** [comment]
> > 用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行
> 
> 前两天用同样的浏览器还正常，现在链接都打不开了，感觉可能脚本有时候可能确实有问题

我用苹果aptv 
手机你去下载播放器吧...
电脑我的浏览器有插件也正常..

**Comment by zsl-157** [comment]
> 
> > > 用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行
> > 
> > 前两天用同样的浏览器还正常，现在链接都打不开了，感觉可能脚本有时候可能确实有问题
> 
> 我用苹果aptv 
> 手机你去下载播放器吧...
> 电脑我的浏览器有插件也正常..
> 

请问你用的什么浏览器插件？

**Comment by zsl-157** [comment]
> > > > https://yang-1989.eu.org/huya/23749096    比如这个链接是访问不了的，好像接口挂了
> > > 
> > > 我看正常啊..埋堆堆
> > > 可能脚本偶尔解析错误？
> > 
> > 用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行
> 
> 前两天用同样的浏览器还正常，现在链接都打不开了，感觉可能脚本有时候可能确实有问题

挂梯子才能访问，但是访问虎牙的直播源返回的是:https://yang-1989.eu.org/videos/x.m3u8，不知道是不是程序里定义的

**Comment by zsl-157** [comment]
> 
> > > 用的什么软件播放的呢？我在手机浏览器和电脑potplayet都不行
> > 
> > 前两天用同样的浏览器还正常，现在链接都打不开了，感觉可能脚本有时候可能确实有问题
> 
> 我用苹果aptv 
> 手机你去下载播放器吧...
> 电脑我的浏览器有插件也正常..
> 

需要挂梯子才行，可能我这里的网络被运营商限制访问了

**Comment by YanG-1989** [comment]
> 需要挂梯子才行，可能我这里的网络被运营商限制访问了

昨天开始eu.org 域名给墙了...

**Comment by YanG-1989** [comment]
> 香港无线新闻网链接不了。

正常我只是没去更新..
https://yang-1989.eu.org/tvb/2

**Comment by zsl-157** [comment]
> 
> > 需要挂梯子才行，可能我这里的网络被运营商限制访问了
> 
> 昨天开始eu.org 域名给墙了...
> 
> 

是的，应该被墙了有几天了
