### ISSUE TITLE
直播源 CHC动作、高清、家庭没有声音

### ISSUE THREAD

**Issue by MVPjoker** [YanG-1989/m3u#51]
你好，更新了2024年后的新版potplayer 这个软件 您的播放源 这3个频道就处于无声状态

把potplayer 返回2023年版本就可以，不知道是软件的问题 还是直播源的问题。

**Comment by YanG-1989** [comment]
明显是软件问题🌚

**Comment by MVPjoker** [comment]
不好意思，麻烦您了。我切换了旧版播放器。不乱升级了
