### ISSUE TITLE
大量直播源失效

### ISSUE THREAD

**Issue by Yigehaoren8848** [YanG-1989/m3u#52]
ipv6除了卫视和央视，其他大部分失效了，比如数字频道，chc等等

**Comment by YanG-1989** [comment]
> ipv6除了卫视和央视，其他大部分失效了，比如数字频道，chc等等

因为陕西v6失效了，CHC目前已经没v6了。
目前只有黑龙江好的，节目不怎么丰富。

**Comment by zsl-157** [comment]
请问作者有爱好频道的源吗

**Comment by YanG-1989** [comment]
> 请问作者有爱好频道的源吗

爱好是啥？估计没有...
我只有大街源..心情好就整理一下..

**Comment by zsl-157** [comment]
就是类别数字ipv6里的ihot频道，这个源不太好找

**Comment by YanG-1989** [comment]
> 就是类别数字ipv6里的ihot频道，这个源不太好找

不好找...这东西！
目前有看到的好像也是浙江内网的..
