### ISSUE TITLE
卫视央视ipv4直播地址

### ISSUE THREAD

**Issue by Yigehaoren8848** [YanG-1989/m3u#53]
请问作者有卫视和央视ipv4获取直播源的源代码吗

**Comment by YanG-1989** [comment]
> 请问作者有卫视和央视ipv4获取直播源的源代码吗

没有哦，央视频代理的坏掉了。
你快去搞搞百事通的代理..
或者去搞大街源。

**Comment by zsl-157** [comment]
> > 请问作者有卫视和央视ipv4获取直播源的源代码吗
> 
> 没有哦，央视频代理的坏掉了。
> 你快去搞搞百事通的代理..
> 或者去搞大街源。

我正在解析央视频的源，央视哪里坏了，是限制访问次数了吗？百事通和大街源是什么，有地址没

**Comment by YanG-1989** [comment]
> > > 请问作者有卫视和央视ipv4获取直播源的源代码吗
> > 
> > 没有哦，央视频代理的坏掉了。
> > 你快去搞搞百事通的代理..
> > 或者去搞大街源。
> 
> 我正在解析央视频的源，央视哪里坏了，是限制访问次数了吗？百事通和大街源是什么，有地址没

央视频多了参数...等大佬分享吧。
自己找吧..百事通我懒！
v4时效性太差了…

**Comment by zsl-157** [comment]
是的，v4好像为数不多的几个平台有，咪咕和央视频，别的不知道了，央视频我快搞出来了，就是麻烦了点

**Comment by YanG-1989** [comment]
> 是的，v4好像为数不多的几个平台有，咪咕和央视频，别的不知道了，央视频我快搞出来了，就是麻烦了点

- 大腿..要逆向出来新的php了吗?

**Comment by zsl-157** [comment]
> > 是的，v4好像为数不多的几个平台有，咪咕和央视频，别的不知道了，央视频我快搞出来了，就是麻烦了点
> 
> - 大腿..要逆向出来新的php了吗?

py的，快了，参数太多了，用py调用的js，搞了两三天了

**Comment by YanG-1989** [comment]
> > > 是的，v4好像为数不多的几个平台有，咪咕和央视频，别的不知道了，央视频我快搞出来了，就是麻烦了点
> > 
> > - 大腿..要逆向出来新的php了吗?
> 
> py的，快了，参数太多了，用py调用的js，搞了两三天了

恩山的php放出来了....
你可以拿去参考..

**Comment by zsl-157** [comment]
恩山？有地址没

**Comment by YanG-1989** [comment]
> 恩山？有地址没

论坛名字...自己进去了就能看到了！

**Comment by zsl-157** [comment]
> > 恩山？有地址没
> 
> 论坛名字...自己进去了就能看到了！

恩山论坛不让访问了😂，网页端的我自己搞出来了，就是api调用有次数限制，m3u8还不知道有没有过期时间，可能要到app抓包，这个我不太擅长，恩山的有次数限制吗？能不能把代码发我一下，我瞅一下看看是不是app端的

**Comment by zsl-157** [comment]
看到源码了，和我抓到的api不一样

**Comment by Jeffreyjjf** [comment]
等待各位大佬分享

**Comment by zsl-157** [comment]
> 等待各位大佬分享

搞出来了就是五分钟后断流，正在研究看怎么解决，只有mytv这个仓库的ipv4可以使用，不过我不太懂kt，参数太多了，还不知道哪个参数出的问题

**Comment by zsl-157** [comment]
已经解决断流问题，央视频已经可以不断流播放了，目前处于测试阶段，只测试了一个频道，等我改好代码分享给大家使用

**Comment by YanG-1989** [comment]
> 等待各位大佬分享

目前央视频有静态的，我的完整版订阅里面有...

**Comment by Yigehaoren8848** [comment]
央视频ipv4可用了，没有断流，https://github.com/Yigehaoren8848/live

**Comment by Jeffreyjjf** [comment]
> 央视频ipv4可用了，没有断流，https://github.com/Yigehaoren8848/live

怎麼使用

**Comment by Yigehaoren8848** [comment]
配置nodejs和py环境，然后运行index.py，我正要做一个修改，用docker会更方便一点

**Comment by YanG-1989** [comment]
> 配置nodejs和py环境，然后运行index.py，我正要做一个修改，用docker会更方便一点

..是的要放docker才方便.
静态的央视频挂掉了！

**Comment by Yigehaoren8848** [comment]
> > 配置nodejs和py环境，然后运行index.py，我正要做一个修改，用docker会更方便一点
> 
> ..是的要放docker才方便.
> 静态的央视频挂掉了！

央视频好像都不太稳定，经常变参数吧，以后还是要把咪咕也搞一下
