### ISSUE TITLE
TiviMate添加“订阅地址「懒人必备」”失败

### ISSUE THREAD

**Issue by willhcz** [YanG-1989/m3u#54]
[订阅地址「懒人必备」](https://yang-1989.eu.org/m3u/Gather)
在TiviMate中添加失败，提示：“错误，处理节目列表时出现错误。确认输入的数据正确，并检查你的网络连接。”
请问这个有办法解决吗，我注意到这个地址是无法直接打开的，是否是因为加密导致无法添加？这样的话应该用什么软件使用这个源？

**Comment by YanG-1989** [comment]
> [订阅地址「懒人必备」](https://yang-1989.eu.org/m3u/Gather)
> 
> 在TiviMate中添加失败，提示：“错误，处理节目列表时出现错误。确认输入的数据正确，并检查你的网络连接。”
> 
> 请问这个有办法解决吗，我注意到这个地址是无法直接打开的，是否是因为加密导致无法添加？这样的话应该用什么软件使用这个源？

你不是正版的吧？
把UA自己填上去就行了...
还有2.1.5版本也不行

**Comment by willhcz** [comment]
> Owner

用的是“[xiaiohuan](https://github.com/xiaiohuan)”发布的2.1.5，也尝试过了2.8.0，都是一样的错误提示。可否请教一下，UA是什么意思？我看软件内只有“输入地址”这个位置，感谢！

**Comment by YanG-1989** [comment]
> 用的是“[xiaiohuan](https://github.com/xiaiohuan)”发布的2.1.5，也尝试过了2.8.0，都是一样的错误提示。可否请教一下，UA是什么意思？我看软件内只有“输入地址”这个位置，感谢！
> 
> 
> 
> （另外还尝试了用IPTV-Pro-6.2.3，输入订阅地址后同样是载入失败）


UA 没填吧TiviMate

**Comment by Waking87** [comment]
> > 用的是“[xiaiohuan](https://github.com/xiaiohuan)”发布的2.1.5，也尝试过了2.8.0，都是一样的错误提示。可否请教一下，UA是什么意思？我看软件内只有“输入地址”这个位置，感谢！
> > （另外还尝试了用IPTV-Pro-6.2.3，输入订阅地址后同样是载入失败）
> 
> UA 没填吧TiviMate 2.7和2.8都正常.. 在设置里面..你看看就会找到。 正版都自带了。

大佬，我的Tivimate的UA那边，输入完无法确认，请问这是啥原因啊？
