### ISSUE TITLE
订阅地址怎么用啊？

### ISSUE THREAD

**Issue by cp358** [YanG-1989/m3u#56]

**Comment by YanG-1989** [comment]
> > > 
> > 
> > 直接播放器里面订阅...还能怎么用？
> 
> https://yang-1989.eu.org/m3u/Gather
> 这个吗，Televizo里添加不行啊，不太会用😑

Televizo  在我白名单里面啊？
直接订阅就行了...
或者你去看看设置里面的UA是不是有什么问题
