### ISSUE TITLE
订阅地址后缀不是m3u

### ISSUE THREAD

**Issue by wsnd5426** [YanG-1989/m3u#57]
新人小白，复制订阅地址，后缀不是m3u或者m3u8，例如https://yang-1989.eu.org/m3u/Gather，怎么使用啊，谢谢，用的推荐的televizo

**Comment by YanG-1989** [comment]
> 新人小白，复制订阅地址，后缀不是m3u或者m3u8，例如https://yang-1989.eu.org/m3u/Gather，怎么使用啊，谢谢，用的推荐的televizo

没关系...里面就是m3u的订阅。
直接订阅就行了

**Comment by wsnd5426** [comment]
> > 新人小白，复制订阅地址，后缀不是m3u或者m3u8，例如[https://yang-1989.eu.org/m3u/Gather，怎么用啊，谢谢，用的推荐的televizo](https://yang-1989.eu.org/m3u/Gather%EF%BC%8C%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%95%8A%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%8C%E7%94%A8%E7%9A%84%E6%8E%A8%E8%8D%90%E7%9A%84televizo)
> 
> 没关系...里面就是m3u的订阅。 直接订阅就行了

谢谢哥
