### ISSUE TITLE
tivimate5.0.4版本港澳频道画面花屏，国内频道画面正常

### ISSUE THREAD

**Issue by yuri0416** [YanG-1989/m3u#60]
之前老版本的tivimate4.8的没有这种问题，5.0.1和5.0.4才添加时频道订阅会好一点，用了半天港澳频道就会花屏，但国内频道的画面是正常的

**Comment by YanG-1989** [comment]
> 之前老版本的tivimate4.8的没有这种问题，5.0.1和5.0.4才添加时频道订阅会好一点，用了半天港澳频道就会花屏，但国内频道的画面是正常的

花屏应该是源头的问题！国内的都是官方的当然稳定....

**Comment by YanG-1989** [comment]
你说的应该是港澳台2分组的源吧...
建议去看stream-link 大佬的..

**Comment by yuri0416** [comment]
哦哦，我是个小白，stream-link是啥，可以麻烦指个路吗

**Comment by YanG-1989** [comment]
> 哦哦，我是个小白，stream-link是啥，可以麻烦指个路吗

http://www.stream-link.org
自己进他主页看看怎么用吧..

**Comment by yuri0416** [comment]
好的～感谢大佬
