### ISSUE TITLE
KODI无法识别

### ISSUE THREAD

**Issue by YuanBaian** [YanG-1989/m3u#64]
https://[yang-1989.eu.org/m3u/Gather](https://yang-1989.eu.org/m3u/Gather)

在KODI中无法识别

**Comment by YanG-1989** [comment]
> https://[yang-1989.eu.org/m3u/Gather](https://yang-1989.eu.org/m3u/Gather)
> 
> 
> 
> 在KODI中无法识别

没在白名单里面..自己改UA吧
不清楚ua是啥..
