### ISSUE TITLE
TiviMate（已检查UA）gather订阅失败

### ISSUE THREAD

**Issue by XuanZai-626** [YanG-1989/m3u#66]
大佬，和前面的issue一样的现象，我加了UA也不行

**Comment by XuanZai-626** [comment]
2.15版本问题

**Comment by YanG-1989** [comment]
> 2.15版本问题

是的..人家问题！

**Comment by Waking87** [comment]
> 大佬，和前面的issue一样的现象，我加了UA也不行

大佬，怎么加UA啊，我在UA输入界面，没法确认，输入完，无法保存。
