### ISSUE TITLE
大佬，为啥央视ipv6没有节目信息

### ISSUE THREAD

**Issue by laiba151a** [YanG-1989/m3u#67]
![17178059216113038692481503699826](https://github.com/YanG-1989/m3u/assets/116480545/167e6e1b-8e31-481e-9175-7edc5471ad37)

**Comment by YanG-1989** [comment]
> ![17178059216113038692481503699826](https://github.com/YanG-1989/m3u/assets/116480545/167e6e1b-8e31-481e-9175-7edc5471ad37)
> 
> 

我没匹配epg..比较懒囧

**Comment by laiba151a** [comment]
能不能考虑配上😁

**Comment by YanG-1989** [comment]
> 能不能考虑配上😁

会匹配的..一个一个来

**Comment by YanG-1989** [comment]
> 能不能考虑配上😁

删掉重新订阅..或者你自己加epg也行
