### ISSUE TITLE
tvbox显示频道列表为空

### ISSUE THREAD

**Issue by gc89925** [YanG-1989/m3u#68]
不论是填写这个地址
https://github.com/YanG-1989/m3u/blob/main/Gather.m3u
还是
https://yang-1989.eu.org/m3u/Gather
都提示
频道列表为空

**Comment by YanG-1989** [comment]
> 不论是填写这个地址
> 
> https://github.com/YanG-1989/m3u/blob/main/Gather.m3u
> 
> 还是
> 
> https://yang-1989.eu.org/m3u/Gather
> 
> 都提示
> 
> 频道列表为空

https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u
这个才是GitHub的地址。

下面那个地址限制了ua..
