### ISSUE TITLE
虎牙似乎挂了

### ISSUE THREAD

**Issue by Pulut** [YanG-1989/m3u#7]
网页上都能播放，加到虎牙的文件里，都播放不了

**Comment by YanG-1989** [comment]
好像是大部分都挂了..> 网页上都能播放，加到虎牙的文件里，都播放不了

**Comment by MattLuoGZ** [comment]
其他几个列表都有不断更新，希望大大看看能不能再更新一下虎牙的列表呢，感恩

**Comment by YanG-1989** [comment]
> 其他几个列表都有不断更新，希望大大看看能不能再更新一下虎牙的列表呢，感恩

代理挂了我也没办法的！最近我都没啥更新就更新了点adult
