### ISSUE TITLE
现在这个时间 源挂了

### ISSUE THREAD

**Issue by aigos** [YanG-1989/m3u#72]
还有就是能换个电视支持的软件吗 tvmate难破解 也太贵了 比水果aptv全端软件贵海了 而且2.1.5好像不支持hevc解码

**Comment by YanG-1989** [comment]
> 还有就是能换个电视支持的软件吗 tvmate难破解 也太贵了 比水果aptv全端软件贵海了 而且2.1.5好像不支持hevc解码

重点电视也没啥软件..影视TV也行你去试下..
