### ISSUE TITLE
Error code 522

### ISSUE THREAD

**Issue by liupinero** [YanG-1989/m3u#73]
Adult.m3u  没响应了
HTTP request sent, awaiting response... 522

**Comment by YanG-1989** [comment]
> Adult.m3u  没响应了
> 
> HTTP request sent, awaiting response... 522 

服务器挂了..晚上再搞吧..
获取不到正常

**Comment by yuri0416** [comment]
gather也挂了吗

**Comment by YanG-1989** [comment]
> gather也挂了吗

同一台服务器当然了...
昨晚就搞好了...
