### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Evin-he** [YanG-1989/m3u#74]
大佬你好，我想请问一下，我用的iOS的ntplayer播放Gather里的有些频道，他显示请保持订阅IP与观看IP一致，这个是什么意思啊，我该如何解决？

**Comment by YanG-1989** [comment]
> 大佬你好，我想请问一下，我用的iOS的ntplayer播放Gather里的有些频道，他显示请保持订阅IP与观看IP一致，这个是什么意思啊，我该如何解决？
> 
> 

nt不可以修改UA的话就没办法...
UA也要求一致..

**Comment by Evin-he** [comment]
好的大佬，谢谢解答
---- Replied Message ----
***@***.***>Date06/20/2024 01:53 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [YanG-1989/m3u] 1 (Issue #74)
大佬你好，我想请问一下，我用的iOS的ntplayer播放Gather里的有些频道，他显示请保持订阅IP与观看IP一致，这个是什么意思啊，我该如何解决？
nt不可以修改UA的话就没办法...
UA也要求一致..

**Comment by YanG-1989** [comment]
> 好的大佬，谢谢解答

这软件昨天才刚刚回归你就问了！
app做得挺好的...(๑•̀ㅂ•́)و✧

**Comment by Evin-he** [comment]
> > 好的大佬，谢谢解答
> 
> 这软件昨天才刚刚回归你就问了！ app做得挺好的...(๑•̀ㅂ•́)و✧
我的ios系统13.5只能下载这个，有些功能还用不上，app确实是好app

**Comment by Evin-he** [comment]
> > 好的大佬，谢谢解答
> 
> 这软件昨天才刚刚回归你就问了！ app做得挺好的...(๑•̀ㅂ•́)و✧ 我的ios系统13.5只能下载这个，有些功能还用不上，app确实是好app

刚才看了一下商店，确实是上线了显示更新，手贱点了更新以后开始闪退了！哎，好烦！
