### ISSUE TITLE
不同软件会显示订阅ip与观看ip不一致

### ISSUE THREAD

**Issue by snownightg** [YanG-1989/m3u#75]
安卓用tivimate就显示订阅ip与观看ip不一致的画面提示无法观看
ipad用aptv就可以看，不知道什么原因。另外请问有tg交流群吗？这样交流和反馈能方便一些
![IMG_0565](https://github.com/YanG-1989/m3u/assets/43474435/fd73d3bc-2e67-46fd-9b08-d1966df060d8)
![IMG_0566](https://github.com/YanG-1989/m3u/assets/43474435/6ab58b32-4f77-490c-9f7b-42f29d379eeb)

**Comment by YanG-1989** [comment]
> 安卓用tivimate就显示订阅ip与观看ip不一致的画面提示无法观看
> 
> ipad用aptv就可以看，不知道什么原因。另外请问有tg交流群吗？这样交流和反馈能方便一些
> 

你可以在APTV的TG群找到我👌...
我自己没建群..
TiviMate 需要设置UA..
你可以在提问题区找到相关的答案.
因为我特意开了一个话题..

**Comment by snownightg** [comment]
> > 安卓用tivimate就显示订阅ip与观看ip不一致的画面提示无法观看
> > ipad用aptv就可以看，不知道什么原因。另外请问有tg交流群吗？这样交流和反馈能方便一些
> 
> 你可以在APTV的TG群找到我👌... 我自己没建群.. TiviMate 需要设置UA.. 你可以在提问题区找到相关的答案. 因为我特意开了一个话题..

感谢回复，看来只能买正版了。我的设备没有root所以不能解锁高级版

**Comment by YanG-1989** [comment]
> 感谢回复，看来只能买正版了。我的设备没有root所以不能解锁高级版

直接用开心版也可以..
不是长期看电视，没必要一定用正版！
目前正版唯一的好处支持mpd..
长期观看的当然还是建议正版.

**Comment by huanghaoran24** [comment]
MyTV是不是看不了 翡翠台4k

**Comment by YanG-1989** [comment]
> MyTV是不是看不了 翡翠台4k

如果其他能看..4K 应该没问题的

**Comment by bbzz127** [comment]
你好,我和楼主有同样的问题,apple tv可以看,mac 上不行,也是有同样的提示

**Comment by YanG-1989** [comment]
> 你好,我和楼主有同样的问题,apple tv可以看,mac 上不行,也是有同样的提示

你改UA了

**Comment by bbzz127** [comment]
不好意思，UA是什么意思？怎么改回来呢？

**Comment by huanghaoran24** [comment]
MyTV没办法![Uploading IMG_0557.png…]()

**Comment by YanG-1989** [comment]
> 不好意思，UA是什么意思？怎么改回来呢？

aptv如果没动过多刷新几次..

**Comment by YanG-1989** [comment]
> MyTV没办法观看[Uploading IMG_0557.png…]()

看不到图..不知道原因！

**Comment by bbzz127** [comment]
好的，谢谢大神
