### ISSUE TITLE
移动网络看不了港澳台

### ISSUE THREAD

**Issue by dsfsdfssa2013** [YanG-1989/m3u#78]
大佬，这几天移动的网络看港澳台像限流了一样，很卡，其他分组没问题，用公司电信的网络又不会卡，这是咋回事啊，之前看都不卡，

**Comment by YanG-1989** [comment]
> 大佬，这几天移动的网络看港澳台像限流了一样，很卡，其他分组没问题，用公司电信的网络又不会卡，这是咋回事啊，之前看都不卡，

港马台分组是吗？
建议挂节点.

**Comment by YanG-1989** [comment]
最近好像移动对跨区网络做调整，目前有点问题。如果其他网络正常，只能说明运营商问题。

**Comment by dsfsdfssa2013** [comment]
本人新手，不套cf是啥意思。- -
