### ISSUE TITLE
使用影视仓加载会显示订阅ip与观看ip不一致

### ISSUE THREAD

**Issue by ashsteins** [YanG-1989/m3u#79]
使用影视仓加载会显示订阅ip与观看ip不一致

**Comment by luii2020** [comment]
用iplay tv看港台也是这样

**Comment by YanG-1989** [comment]
> 用iplay tv看港台也是这样

UA不一致..iplay我记得设置了白名单

**Comment by YanG-1989** [comment]
> 使用影视仓加载会显示订阅ip与观看ip不一致

多刷新几次吧

**Comment by ashsteins** [comment]
用的5.0.35.1版本，仍然是这样

**Comment by YanG-1989** [comment]
> 用的5.0.35.1版本，仍然是这样

用的tivimate？
正版我记得刷新订阅就行了..多刷几次

**Comment by ashsteins** [comment]
可能是因为我PC用的vpn，然后模拟器mumu里面的IP和外面不一致导致的

**Comment by ashsteins** [comment]
用的影视仓

**Comment by huanghaoran24** [comment]
我用aptv也会显示ip不一致

**Comment by Fanzf-926** [comment]
我也是 tvbox 影视仓都不行 咪咕奥运那边都显示ip不一致

**Comment by YanG-1989** [comment]
> 我用aptv也会显示ip不一致
> 
说了多刷新几次..
其他软件刷新不成功ua也要一致
