### ISSUE TITLE
使用TVBOX播放时咪咕的订阅会突然失效

### ISSUE THREAD

**Issue by PeppaTom** [YanG-1989/m3u#81]
最近奥运会比赛多，看得比较频繁，我用的是TVBOX影视，在安卓TV盒子上观看，偶尔会出现咪咕订阅突然失效的情况，具体表现如下：
当前咪咕频道播放正常，但是切换到其他咪咕频道（包括咪咕的TV台，以及咪咕的奥运赛事）时，会出现播放地址加载失败或者THE END.....界面，在TVBOX软件设置中重新获取一下订阅即可解决。

**Comment by YanG-1989** [comment]
> 最近奥运会比赛多，看得比较频繁，我用的是TVBOX影视，在安卓TV盒子上观看，偶尔会出现咪咕订阅突然失效的情况，具体表现如下：
> 
> 当前咪咕频道播放正常，但是切换到其他咪咕频道（包括咪咕的TV台，以及咪咕的奥运赛事）时，会出现播放地址加载失败或者THE END.....界面，在TVBOX软件设置中重新获取一下订阅即可解决。
> 
> 

the end代表链接失效了...
可能是每天6个小时更新一次订阅的缘故吧
