### ISSUE TITLE
epg无法正常

### ISSUE THREAD

**Issue by bike3097a** [YanG-1989/m3u#82]
使用epg，出现502，IPTV 文件处理。
![Screenshot_20240729_083441_com android chrome](https://github.com/user-attachments/assets/0bf14396-0197-42ad-b2f9-b91077591cb1)

**Comment by YanG-1989** [comment]
> 使用epg，出现502，IPTV 文件处理。
> 
> ![Screenshot_20240729_083441_com android chrome](https://github.com/user-attachments/assets/0bf14396-0197-42ad-b2f9-b91077591cb1)
> 
> 

我自己试了正常...你epg地址错了吧

**Comment by bike3097a** [comment]
不可能错误呀，我又不是手动改的

**Comment by YanG-1989** [comment]
> 不可能错误呀，我又不是手动改的

看你的浏览器显示的地址就不对...

**Comment by bike3097a** [comment]
不好意思，刚刚测试，现在正常了。
