### ISSUE TITLE
ipv6直播源显示超时

### ISSUE THREAD

**Issue by liuchengze12138** [YanG-1989/m3u#83]
ipv6直播源显示超时

**Comment by YanG-1989** [comment]
> ipv6直播源显示超时

湖北和海南v6挂了...晚上再说吧

**Comment by liuchengze12138** [comment]
ipv6直播源还是超时啊
![Uploading 截屏2024-07-30 14.56.15.png…]()

**Comment by liuchengze12138** [comment]
![Uploading 截屏2024-07-30 14.56.15.png…]()
