### ISSUE TITLE
频道名字能去掉 IPV6 字样吗？

### ISSUE THREAD

**Issue by smgfw** [YanG-1989/m3u#84]
占位导致换台列表里各地卫视的名称显示不全。

**Comment by YanG-1989** [comment]
> 占位导致换台列表里各地卫视的名称显示不全。

你的软件问题吧，卫视名字已经很短了.

**Comment by smgfw** [comment]
> > 占位导致换台列表里各地卫视的名称显示不全。
> 
> 你的软件问题吧，卫视名字已经很短了.

有可能是软件默认的字体太大了，我用的是 https://github.com/lizongying/my-tv-0 ，换台列表页面的显示效果是： 
CCTV1[IPV... 
CCTV5[IPV...
CCTV5+[IP...
CCTV13[IP...

北京...
天津...
江苏...

**Comment by YanG-1989** [comment]
这个和我没什么关系....
自己重新编辑吧..

**Comment by dxxjg** [comment]
> 这个和我没什么关系....
> 自己重新编辑吧..

谢谢，找到解决办法了，电视设置字体调小即可。
