### ISSUE TITLE
用televizo添加了还是没显示出来？

### ISSUE THREAD

**Issue by deexx888** [YanG-1989/m3u#85]
![微信图片_20240730020427](https://github.com/user-attachments/assets/09131bba-a686-47d5-87cf-01779375ccf6)

**Comment by YanG-1989** [comment]
> ![微信图片_20240730020427](https://github.com/user-attachments/assets/09131bba-a686-47d5-87cf-01779375ccf6)
> 
> 

你下载的版本有问题...

**Comment by deexx888** [comment]
我下载过旧的版本还是不行，我添加了其他的也行[
![微信图片_20240730181033](https://github.com/user-attachments/assets/c5f7cf67-1d39-4672-ae65-7d9e4c0be3d0)

**Comment by deexx888** [comment]
我试过了旧的版本还是不行，添加过其它的可以看

**Comment by deexx888** [comment]
> > 我试过了旧的版本还是不行，添加过其它的可以看
> 
> https://t.me/WangPanBOT?start=file7b780a88f2c6c730
> 
> 下载这个版本去试下.. 或者下载官方的..

官方的也不行，下载你这个可以了感谢

**Comment by YanG-1989** [comment]
或者自定义UA也行...反正都可以达到目的！
