### ISSUE TITLE
mytv无法播放是什么问题

### ISSUE THREAD

**Issue by hyx08713** [YanG-1989/m3u#86]
mytv无法播放

**Comment by YanG-1989** [comment]
> mytv无法播放

你的播放器支持？

**Comment by luii2020** [comment]
哪个播发器才支持？

**Comment by YanG-1989** [comment]
> 哪个播发器才支持？

支持mpd的播放器...
OTT Tivimate 影视tv 极致....
目前我就知道这些..
你自己去找吧

**Comment by snownightg** [comment]
> 我

ott改了ua好一段时间可以用，过两天就不行了不知道因为什么。提示订阅地址与ip不符，解决方案是重新载入供应商，但是总这么操作比较繁琐家里人又不怎么会…

**Comment by YanG-1989** [comment]
> > 我
> 
> ott改了ua好一段时间可以用，过两天就不行了不知道因为什么。提示订阅地址与ip不符，解决方案是重新载入供应商，但是总这么操作比较繁琐家里人又不怎么会…

换个软件...
打开软件就自动更新订阅那种..
或者你自己稳定ip
防盗没办法..本来服务器流量就不小了。

**Comment by luii2020** [comment]
> > > 我
> > 
> > 
> > ott改了ua好一段时间可以用，过两天就不行了不知道因为什么。提示订阅地址与ip不符，解决方案是重新载入供应商，但是总这么操作比较繁琐家里人又不怎么会…
> 
> 换个软件... 打开软件就自动更新订阅那种.. 或者你自己稳定ip 防盗没办法..本来服务器流量就不小了。 我不清楚你经常看什么节目.. 香港的你可以考虑直接看mytv

iplaytv的ua改什么才能用？

**Comment by YanG-1989** [comment]
> iplaytv的ua改什么才能用？

这个软件好像不支持mytv
代理源，反正不是UA就是IP问题

**Comment by jerryc127** [comment]
aptv支持么

**Comment by YanG-1989** [comment]
> aptv支持么

ios 基本上没希望支持

**Comment by z574509027** [comment]
windows端有能播放的设备吗

**Comment by YanG-1989** [comment]
> windows端有能播放的设备吗
> 
> 

用浏览器插件

**Comment by z574509027** [comment]
老哥麻烦您再提示下装哪个浏览器插件？谢谢



在 2024-12-23 21:30:20，"大葱" ***@***.***> 写道：

windows端有能播放的设备吗

用浏览器插件

**Comment by YanG-1989** [comment]
> 老哥麻烦您再提示下装哪个浏览器插件？谢谢
> 
> 
> 
> 在 2024-12-23 21:30:20，"大葱" ***@***.***> 写道：
> 
> windows端有能播放的设备吗
> 
> 用浏览器插件
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

我的tg群写了地址...我懒得复制
