### ISSUE TITLE
兄弟要不要拉一下TG群，防失联啊这种

### ISSUE THREAD

**Issue by moke8** [YanG-1989/m3u#9]
兄弟要不要拉一下TG群，防失联啊这种，也方便大家交流交流，互通有无

**Comment by YanG-1989** [comment]
> 兄弟要不要拉一下TG群，防失联啊这种，也方便大家交流交流，互通有无

失联不了…除非不我玩手机了偶尔会上来看看

**Comment by danlan12** [comment]
我也赞成拉个群交流一下，哈哈
