### ISSUE TITLE
migu直播经常出现“请保持订阅IP与观看IP一致”，这是源的问题，还是客户端设置问题？

### ISSUE THREAD

**Issue by flyhh008** [YanG-1989/m3u#90]
migu直播经常出现“请保持订阅IP与观看IP一致”，这是源的问题，还是客户端设置问题？

**Comment by YanG-1989** [comment]
> migu直播经常出现“请保持订阅IP与观看IP一致”，这是源的问题，还是客户端设置问题？

我源设置防盗...最好固定节点吧
如果ip跳了 就会出现这个问题..

**Comment by dawnsummit** [comment]
但是我觉得你的ip检测好像有点问题，会误判。

**Comment by YanG-1989** [comment]
> 但是我觉得你的ip检测好像有点问题，会误判。

就是你ip跳了..
你如果永固定节点还会失效  那才是检测问题。

**Comment by imvane** [comment]
我用固定节点就会提示 反而用移动网络没问题

**Comment by YanG-1989** [comment]
> 我用固定节点就会提示 反而用移动网络没问题

看你自己喜欢..
你可以直接把iill 分流到直连

**Comment by imvane** [comment]
按置顶帖子设置了 订阅正常了
另外楼主提个建议 可否把订阅频道精简下 
因为比如央视频道 相对fan'ming'ming会慢不少
