### ISSUE TITLE
部分分区比如台湾台无法观看“请保持订阅IP与观看IP一致”

### ISSUE THREAD

**Issue by ljbkevin** [YanG-1989/m3u#91]
大佬，部分分区比如台湾台无法观看“请保持订阅IP与观看IP一致”，其他大部分台如香港台没有问题。目前appletv使用梯子的自动分流规则，是否是因为分流规则导致台湾台的流量走了梯子？才出现了IP不一致无法观看？求问解决方案。感谢

**Comment by YanG-1989** [comment]
> 大佬，部分分区比如台湾台无法观看“请保持订阅IP与观看IP一致”，其他大部分台如香港台没有问题。目前appletv使用梯子的自动分流规则，是否是因为分流规则导致台湾台的流量走了梯子？才出现了IP不一致无法观看？求问解决方案。感谢

可能部分频道坏了...
你需要告知..

**Comment by YanG-1989** [comment]
还有你需要留言告诉我你的软件是啥！

**Comment by ljbkevin** [comment]
> 还有你需要留言告诉我你的软件是啥！

大佬，我用的是APTV这个APP。

**Comment by YanG-1989** [comment]
> > 还有你需要留言告诉我你的软件是啥！
> 
> 大佬，我用的是APTV这个APP。

那你肯定乱改ua了..恢复默认
