### ISSUE TITLE
已经通过固定节点订阅和观看还是出现了“请保持订阅ip与观看ip一致”

### ISSUE THREAD

**Issue by lucasyippp** [YanG-1989/m3u#93]
平时看翡翠台等港台比较多，已经用了固定节点而且从梯子后台可以看到流量都是从固定节点出去的，但是也一致提示“请保持订阅ip与观看ip一致”，前一段时间偶尔看看好像还没问题，最近看基本上都弹出这个提示。大佬可以帮忙看看吗

**Comment by YanG-1989** [comment]
> 平时看翡翠台等港台比较多，已经用了固定节点而且从梯子后台可以看到流量都是从固定节点出去的，但是也一致提示“请保持订阅ip与观看ip一致”，前一段时间偶尔看看好像还没问题，最近看基本上都弹出这个提示。大佬可以帮忙看看吗

昨天都挂了了...
可以翻墙建议固件节点用
http://www.stream-link.org

这个大佬的稳定..

如果固定节点还显示ip不一致..
就是软件问题了..不清楚你使用的什么软件。

**Comment by lucasyippp** [comment]
翻了之前closed的讨论用了这个大佬的链接好像也是同样的情况。。。用的是软路由的openclash应该不会有这个情况才对

**Comment by lucasyippp** [comment]
苹果端用的是aptv，电脑端用的是potplayer

**Comment by YanG-1989** [comment]
> 苹果端用的是aptv，电脑端用的是potplayer

我的订阅如果固定ip，刷新后还出现不一致。
pot 应该没什么问题，aptv你肯定修改默认ua了，恢复默认。

**Comment by lucasyippp** [comment]
> > 苹果端用的是aptv，电脑端用的是potplayer
> 
> 我的订阅如果固定ip，刷新后还出现不一致。
> pot 应该没什么问题，aptv你肯定修改默认ua了，恢复默认。

好像也还是不行，没有改过ua，有点子奇怪

**Comment by YanG-1989** [comment]
没可能..
ip固定的话，用的是没改过UA的aptv，不可能出现这个情况。
自己找问题吧..重点都告诉你了。
