### ISSUE TITLE
怎么在网页中嵌入直播链接

### ISSUE THREAD

**Issue by SEhzm** [YanG-1989/m3u#95]
怎么在网页中嵌入直播链接

**Comment by YanG-1989** [comment]
> 怎么在网页中嵌入直播链接

ChatGPT...
很简单几句话就告诉你了。

**Comment by SEhzm** [comment]
直播流嵌入会跳到你的订阅页面，或者连不通，potplayer能连通

**Comment by YanG-1989** [comment]
> 直播流嵌入会跳到你的订阅页面，或者连不通，potplayer能连通

因为我做限制了..把我的源放到网页干什么..
