### ISSUE TITLE
大佬港台马1总是不稳定

### ISSUE THREAD

**Issue by Daniel296VG** [YanG-1989/m3u#96]
RT
比如我点进去，所有的频道只能看个十秒钟就断线了，刷新之后就显示“the end”的视频，港台马里面所有的频道都是这样，很奇怪，换了很多个节点也重置了链接好像一直不太行，想问问要咋解决，很想看东森电影台！
![D10AF4E8-3679-4F18-A029-51E496993556](https://github.com/user-attachments/assets/aac7d047-589e-4482-9d23-00b57d00ba32)

**Comment by Daniel296VG** [comment]
我是APTV哈

**Comment by YanG-1989** [comment]
因为源头坏了...
暂时恢复了一部分台..
具体什么台恢复了，你自己去测试吧...

**Comment by YanG-1989** [comment]
如果你在aptv群里，下次就直接@我就好了。一般GitHub偶尔才看一眼

**Comment by Daniel296VG** [comment]
大佬，群在哪里😭😭

**Comment by YanG-1989** [comment]
> 大佬，群在哪里😭😭

我没群啊..我都呆在人家群里..

**Comment by andyTV123** [comment]
一样的，最近这源越来越不行了……

**Comment by YanG-1989** [comment]
> 一样的，最近这源越来越不行了……

白嫖有得看就不错了..
想要稳定可以去看stream的

**Comment by syb1220** [comment]
> 一样的，最近这源越来越不行了……
> 白嫖有得看就不错了..
> 想要稳定可以去看stream的

确实不错了 佛系大佬
