### ISSUE TITLE
咪咕全网的IPV4频道看不了

### ISSUE THREAD

**Issue by andyzeng0410** [YanG-1989/m3u#98]
咪咕全网的IPV4频道家里的宽带看不了，但是手机信号可以看，都是电信的，这是咋回事？

**Comment by YanG-1989** [comment]
> 咪咕全网的IPV4频道家里的宽带看不了，但是手机信号可以看，都是电信的，这是咋回事？

分流走代理...
你手机的代理软件和电视的不一样吧..

**Comment by andyzeng0410** [comment]
> > 咪咕全网的IPV4频道家里的宽带看不了，但是手机信号可以看，都是电信的，这是咋回事？
> 
> 分流走代理...
> 你手机的代理软件和电视的不一样吧..

都没走代理，直连的…

**Comment by YanG-1989** [comment]
DOMAIN-SUFFIX,gslbservzqhsw,PROXY
DOMAIN-SUFFIX,zqhswlive,PROXY

分流规则这样写..
或者部署肥羊的新项目吧..
前两天出来的二选一..

**Comment by andyzeng0410** [comment]
> DOMAIN-SUFFIX,gslbservzqhsw,PROXY
> DOMAIN-SUFFIX,zqhswlive,PROXY
> 
> 分流规则这样写..
> 或者部署肥羊的新项目吧..
> 前两天出来的二选一..
> 

新项目是？麻烦大佬给个地址

**Comment by YanG-1989** [comment]
自己去肥羊群找吧 docker项目...
半个老项目吧...实际上没什么用看需求.
