### ISSUE TITLE
咪咕的体育看不了

### ISSUE THREAD

**Issue by Jimmiewen** [YanG-1989/m3u#99]
大佬好，gather下咪咕体育分类看不了，一直提示订阅与播放ip不一致。除了Wi-Fi，还测试了手机5g更新订阅及播放，同样出现上述提示，请问如何解决？

**Comment by Jimmiewen** [comment]
TiviMate 2.1.5 版本, 现在只需要在设置里面 填写UA : okhttp; 解决了，谢谢大佬。另外想请教下，tivimate的其他版本是否需要填写UA？

**Comment by Jimmiewen** [comment]
楼主你好，咪咕体育分类里的英超付费场次提示 the end，是本身就看不了吗？比如今晚的曼城对切尔西的比赛，就是提示the end。

**Comment by YanG-1989** [comment]
显示“结束“代表这是收费场次.
我没开英超会员看不了..
这时候你去咪咕全网里面看就行了...
咪咕全网分组所有比赛都有,只是比赛的时候要自己找..

**Comment by Jimmiewen** [comment]
谢谢楼主，还想请问下tivimate正版和破解会员版有何区别？我在该软件官网看到能免费下载，google商店里该软件也不需要付费呀？

**Comment by YanG-1989** [comment]
> 谢谢楼主，还想请问下tivimate正版和破解会员版有何区别？我在该软件官网看到能免费下载，google商店里该软件也不需要付费呀？

盗版有bug，节目表会失效。
正版支持mpd格式..
可以播放mytv的源..
不看香港节目可以无视..

**Comment by Jimmiewen** [comment]
谢谢楼主，我看您帖子里说tivimate2.1.5添加UA后会跟stream-link冲突，但是我开心版的用下来，看streamlink没有啥影响

**Comment by YanG-1989** [comment]
> 谢谢楼主，我看您帖子里说tivimate2.1.5添加UA后会跟stream-link冲突，但是我开心版的用下来，看streamlink没有啥影响

可能stream 改规则了吧...
之前ua okhttp 播放不了..
